/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime --config workers/blaze-field-do/wrangler.toml workers/blaze-field-do/env.d.ts` (hash: 56b32ad5323baa6ca6dc49d4bc24d8a4)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "GameRoom";
	}
	interface Env {
		GAME_ROOM: DurableObjectNamespace<import("./index").GameRoom>;
	}
}
interface Env extends Cloudflare.Env {}
