/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: dab5e45b67e0c94a60f4072212d69f8e)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		KV: KVNamespace;
		DB: D1Database;
	}
}
interface Env extends Cloudflare.Env {}
