name = "blazesports-content"
compatibility_date = "2025-01-01"
main = "index.ts"

# Scheduled triggers for automated content generation
[triggers]
crons = ["*/15 * * * *", "0 */6 * * *"]

# Environment variables (set via wrangler secret)
[vars]
# DATABASE_URL - set via wrangler secret put DATABASE_URL
# ANTHROPIC_API_KEY - set via wrangler secret put ANTHROPIC_API_KEY
# OPENAI_API_KEY - set via wrangler secret put OPENAI_API_KEY
# GOOGLE_GEMINI_API_KEY - set via wrangler secret put GOOGLE_GEMINI_API_KEY
# CONTENT_SECRET - set via wrangler secret put CONTENT_SECRET

# KV namespace for caching
[[kv_namespaces]]
binding = "CACHE"
id = "a53c3726fc3044be82e79d2d1e371d26"

# Analytics Engine for monitoring
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "bsi_content_analytics"

# Routes (if deploying to custom domain)
# routes = [
#   { pattern = "api.blazesportsintel.com/content/*", zone_name = "blazesportsintel.com" }
# ]
