/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime --config workers/synthetic-monitor/wrangler.toml workers/synthetic-monitor/env.d.ts` (hash: 7b33ea90e0101405a9eeda6eb2341058)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		MONITOR_KV: KVNamespace;
		DATA_LAKE: R2Bucket;
	}
}
interface Env extends Cloudflare.Env {}
