/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 817f69e93fa56a2c9b18b6416671ceb7)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		BSI_AI_CACHE: KVNamespace;
		BSI_KEYS: KVNamespace;
	}
}
interface Env extends Cloudflare.Env {}
