repos:
  - repo: local
    hooks:
      - id: ui-protection
        name: UI Protection Validation
        entry: npm run ui:validate
        language: system
        files: \.(html|css|js|ts|tsx)$
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        
      - id: context7-validation
        name: Context7 Integration Validation
        entry: npm run context7:validate
        language: system
        files: ^context7-enhanced/.*\.ts$
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        
      - id: brand-color-protection
        name: Brand Color Protection
        entry: node scripts/validate-ui-protection.js
        language: system
        files: \.(html|css|js|ts|tsx)$
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        
      - id: drift-detection
        name: Data Drift Detection
        entry: python observability/drift/drift_detector.py --pre-commit
        language: system
        files: ^data/.*|^api/.*|^models/.*
        pass_filenames: false
        always_run: false
        stages: [pre-commit]