// Mock data structures - represents what real NCAA/D1Baseball data would look like

export const mockLiveGames = [
  {
    id: 'game-001',
    status: 'live',
    date: '2025-03-15',
    scheduledTime: '2:00 PM CT',
    venue: 'Alex Box Stadium',
    inning: {
      number: 7,
      half: 'Top',
    },
    situation: {
      outs: 2,
      runners: 'Runners on 1st & 2nd',
    },
    awayTeam: {
      id: 'texas',
      name: 'Texas',
      abbreviation: 'TEX',
      conference: 'SEC',
      record: '12-3, 3-1 SEC',
      score: 4,
    },
    homeTeam: {
      id: 'lsu',
      name: 'LSU',
      abbreviation: 'LSU',
      conference: 'SEC',
      record: '15-2, 4-0 SEC',
      score: 6,
    },
    currentPitcher: {
      name: 'Javen Coleman',
      number: 17,
      pitches: 89,
      era: '3.24',
    },
    currentBatter: {
      name: 'Max Belyeu',
      number: 5,
      avg: '.342',
    },
  },
  {
    id: 'game-002',
    status: 'live',
    date: '2025-03-15',
    scheduledTime: '3:00 PM CT',
    venue: 'Blue Bell Park',
    inning: {
      number: 5,
      half: 'Bottom',
    },
    situation: {
      outs: 1,
      runners: 'Runner on 3rd',
    },
    awayTeam: {
      id: 'arkansas',
      name: 'Arkansas',
      abbreviation: 'ARK',
      conference: 'SEC',
      record: '14-4, 2-2 SEC',
      score: 3,
    },
    homeTeam: {
      id: 'texas-am',
      name: 'Texas A&M',
      abbreviation: 'TAMU',
      conference: 'SEC',
      record: '11-5, 2-1 SEC',
      score: 5,
    },
    currentPitcher: {
      name: 'Will McEntire',
      number: 30,
      pitches: 67,
      era: '2.87',
    },
    currentBatter: {
      name: 'Kaeden Kent',
      number: 13,
      avg: '.298',
    },
  },
  {
    id: 'game-003',
    status: 'final',
    date: '2025-03-15',
    scheduledTime: '12:00 PM CT',
    venue: 'Swayze Field',
    awayTeam: {
      id: 'mississippi-state',
      name: 'Mississippi State',
      abbreviation: 'MSU',
      conference: 'SEC',
      record: '10-6, 1-2 SEC',
      score: 2,
    },
    homeTeam: {
      id: 'ole-miss',
      name: 'Ole Miss',
      abbreviation: 'OM',
      conference: 'SEC',
      record: '13-4, 3-1 SEC',
      score: 7,
    },
  },
];

export const mockBoxScore = {
  lineScore: {
    innings: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    away: {
      innings: [0, 2, 0, 1, 0, 0, 1, 0, 0],
      runs: 4,
      hits: 8,
      errors: 1,
    },
    home: {
      innings: [1, 0, 2, 0, 1, 2, 0, 0, null],
      runs: 6,
      hits: 10,
      errors: 0,
    },
  },
  batting: {
    away: [
      {
        id: 'p1',
        name: 'Jace Jung',
        position: 'SS',
        ab: 4,
        r: 1,
        h: 2,
        rbi: 1,
        bb: 0,
        k: 1,
        seasonAvg: '.368',
      },
      {
        id: 'p2',
        name: 'Max Belyeu',
        position: 'LF',
        ab: 4,
        r: 1,
        h: 1,
        rbi: 0,
        bb: 1,
        k: 2,
        seasonAvg: '.342',
      },
      {
        id: 'p3',
        name: 'Eric Kennedy',
        position: 'RF',
        ab: 4,
        r: 0,
        h: 2,
        rbi: 2,
        bb: 0,
        k: 0,
        seasonAvg: '.315',
      },
      {
        id: 'p4',
        name: 'Will Gasparino',
        position: '1B',
        ab: 3,
        r: 1,
        h: 1,
        rbi: 0,
        bb: 1,
        k: 1,
        seasonAvg: '.287',
      },
      {
        id: 'p5',
        name: 'Jordan Thompson',
        position: 'C',
        ab: 4,
        r: 0,
        h: 1,
        rbi: 0,
        bb: 0,
        k: 2,
        seasonAvg: '.294',
      },
      {
        id: 'p6',
        name: 'Jack ODowd',
        position: '2B',
        ab: 3,
        r: 1,
        h: 1,
        rbi: 1,
        bb: 0,
        k: 0,
        seasonAvg: '.276',
      },
      {
        id: 'p7',
        name: 'Kimble Schuessler',
        position: '3B',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 1,
        seasonAvg: '.248',
      },
      {
        id: 'p8',
        name: 'Mitchell Daly',
        position: 'DH',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 2,
        seasonAvg: '.221',
      },
      {
        id: 'p9',
        name: 'Peyton Graham',
        position: 'CF',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 1,
        seasonAvg: '.267',
      },
    ],
    home: [
      {
        id: 'h1',
        name: 'Tommy White',
        position: '1B',
        ab: 4,
        r: 2,
        h: 3,
        rbi: 2,
        bb: 0,
        k: 0,
        seasonAvg: '.387',
      },
      {
        id: 'h2',
        name: 'Josh Pearson',
        position: 'RF',
        ab: 4,
        r: 1,
        h: 2,
        rbi: 1,
        bb: 0,
        k: 1,
        seasonAvg: '.351',
      },
      {
        id: 'h3',
        name: 'Jared Jones',
        position: 'LF',
        ab: 4,
        r: 1,
        h: 2,
        rbi: 2,
        bb: 0,
        k: 0,
        seasonAvg: '.329',
      },
      {
        id: 'h4',
        name: 'Alex Milmartineau',
        position: 'C',
        ab: 3,
        r: 1,
        h: 1,
        rbi: 0,
        bb: 1,
        k: 0,
        seasonAvg: '.298',
      },
      {
        id: 'h5',
        name: 'Michael Braswell III',
        position: '3B',
        ab: 3,
        r: 0,
        h: 1,
        rbi: 1,
        bb: 0,
        k: 1,
        seasonAvg: '.312',
      },
      {
        id: 'h6',
        name: 'Hayden Travinski',
        position: '2B',
        ab: 3,
        r: 1,
        h: 1,
        rbi: 0,
        bb: 1,
        k: 0,
        seasonAvg: '.276',
      },
      {
        id: 'h7',
        name: 'Ben Nippolt',
        position: 'SS',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 2,
        seasonAvg: '.254',
      },
      {
        id: 'h8',
        name: 'Ethan Frey',
        position: 'DH',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 1,
        seasonAvg: '.239',
      },
      {
        id: 'h9',
        name: 'Josh Stevenson',
        position: 'CF',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 1,
        seasonAvg: '.265',
      },
    ],
  },
  pitching: {
    away: [
      {
        id: 'ap1',
        name: 'Tanner Witt',
        ip: '4.0',
        h: 6,
        r: 4,
        er: 4,
        bb: 2,
        k: 4,
        pitches: 78,
        seasonEra: '3.45',
      },
      {
        id: 'ap2',
        name: 'Andre Duplantier II',
        ip: '2.0',
        h: 3,
        r: 2,
        er: 2,
        bb: 1,
        k: 2,
        pitches: 38,
        seasonEra: '4.12',
      },
      {
        id: 'ap3',
        name: 'Cam Caley',
        ip: '0.2',
        h: 1,
        r: 0,
        er: 0,
        bb: 0,
        k: 1,
        pitches: 12,
        decision: 'L (2-1)',
        seasonEra: '2.87',
      },
    ],
    home: [
      {
        id: 'hp1',
        name: 'Paul Skenes',
        ip: '6.0',
        h: 5,
        r: 3,
        er: 3,
        bb: 1,
        k: 9,
        pitches: 94,
        decision: 'W (4-0)',
        seasonEra: '1.69',
      },
      {
        id: 'hp2',
        name: 'Javen Coleman',
        ip: '1.0',
        h: 2,
        r: 1,
        er: 1,
        bb: 0,
        k: 1,
        pitches: 18,
        seasonEra: '3.24',
      },
      {
        id: 'hp3',
        name: 'Garrett Edwards',
        ip: '2.0',
        h: 1,
        r: 0,
        er: 0,
        bb: 0,
        k: 3,
        pitches: 24,
        decision: 'SV (5)',
        seasonEra: '1.98',
      },
    ],
  },
  advanced: {
    hitters: [
      {
        id: 'p1',
        playerId: 'p1',
        name: 'Jace Jung',
        team: 'Texas',
        side: 'away',
        xBA: 0.318,
        xSLG: 0.587,
        hardHitRate: 0.54,
        barrelRate: 0.18,
        sprayDistribution: {
          pull: 0.46,
          center: 0.31,
          oppo: 0.23,
        },
        trend: [0.32, 0.35, 0.38, 0.42, 0.44],
        highlightIds: ['clip-tex-hr'],
      },
      {
        id: 'p2',
        playerId: 'p2',
        name: 'Max Belyeu',
        team: 'Texas',
        side: 'away',
        xBA: 0.284,
        xSLG: 0.468,
        hardHitRate: 0.41,
        barrelRate: 0.11,
        sprayDistribution: {
          pull: 0.39,
          center: 0.37,
          oppo: 0.24,
        },
        trend: [0.24, 0.26, 0.31, 0.29, 0.28],
        highlightIds: [],
      },
      {
        id: 'h1',
        playerId: 'h1',
        name: 'Tommy White',
        team: 'LSU',
        side: 'home',
        xBA: 0.341,
        xSLG: 0.712,
        hardHitRate: 0.62,
        barrelRate: 0.27,
        sprayDistribution: {
          pull: 0.51,
          center: 0.34,
          oppo: 0.15,
        },
        trend: [0.55, 0.6, 0.63, 0.66, 0.68],
        highlightIds: ['clip-lsu-hr'],
      },
      {
        id: 'h2',
        playerId: 'h2',
        name: 'Josh Pearson',
        team: 'LSU',
        side: 'home',
        xBA: 0.309,
        xSLG: 0.552,
        hardHitRate: 0.48,
        barrelRate: 0.16,
        sprayDistribution: {
          pull: 0.42,
          center: 0.36,
          oppo: 0.22,
        },
        trend: [0.28, 0.31, 0.34, 0.36, 0.39],
        highlightIds: ['clip-lsu-gap'],
      },
    ],
    pitchers: [
      {
        id: 'hp1',
        playerId: 'hp1',
        name: 'Paul Skenes',
        team: 'LSU',
        side: 'home',
        stuffPlus: 134,
        pitchQuality: 94,
        whiffRate: 0.38,
        chaseRate: 0.33,
        avgVelo: 99.4,
        pitchMix: {
          fastball: 0.58,
          slider: 0.29,
          changeup: 0.13,
        },
        trend: [0.34, 0.36, 0.38, 0.4, 0.41],
        highlightIds: ['clip-lsu-k'],
      },
      {
        id: 'hp2',
        playerId: 'hp2',
        name: 'Javen Coleman',
        team: 'LSU',
        side: 'home',
        stuffPlus: 112,
        pitchQuality: 86,
        whiffRate: 0.27,
        chaseRate: 0.24,
        avgVelo: 94.1,
        pitchMix: {
          fastball: 0.49,
          slider: 0.27,
          changeup: 0.24,
        },
        trend: [0.24, 0.26, 0.27, 0.28, 0.29],
        highlightIds: [],
      },
      {
        id: 'ap1',
        playerId: 'ap1',
        name: 'Tanner Witt',
        team: 'Texas',
        side: 'away',
        stuffPlus: 108,
        pitchQuality: 82,
        whiffRate: 0.24,
        chaseRate: 0.21,
        avgVelo: 93.2,
        pitchMix: {
          fastball: 0.52,
          curveball: 0.31,
          changeup: 0.17,
        },
        trend: [0.22, 0.21, 0.23, 0.25, 0.24],
        highlightIds: ['clip-tex-k'],
      },
    ],
    defenders: [
      {
        id: 'h7',
        playerId: 'h7',
        name: 'Ben Nippolt',
        team: 'LSU',
        position: 'SS',
        side: 'home',
        defenderRange: 87,
        outsAboveAverage: 6,
        successRate: 0.91,
        exchangeTime: 0.62,
        armStrength: 91,
        trend: [78, 82, 84, 86, 87],
        highlightIds: ['clip-lsu-defense'],
      },
      {
        id: 'p4',
        playerId: 'p4',
        name: 'Will Gasparino',
        team: 'Texas',
        position: '1B',
        side: 'away',
        defenderRange: 74,
        outsAboveAverage: 2,
        successRate: 0.84,
        exchangeTime: 0.74,
        armStrength: 76,
        trend: [70, 71, 72, 73, 74],
        highlightIds: [],
      },
      {
        id: 'h9',
        playerId: 'h9',
        name: 'Josh Stevenson',
        team: 'LSU',
        position: 'CF',
        side: 'home',
        defenderRange: 91,
        outsAboveAverage: 5,
        successRate: 0.89,
        exchangeTime: 0.61,
        armStrength: 93,
        trend: [86, 87, 88, 90, 91],
        highlightIds: ['clip-lsu-defense'],
      },
    ],
    media: [
      {
        id: 'clip-lsu-hr',
        type: 'video',
        title: 'Tommy White 112 mph rocket',
        description: 'Two-run shot at 24° launch and 112 mph exit velocity.',
        thumbnail: 'https://media.blazesi.com/thumbnails/lsu-hr.jpg',
        assetUrl: 'https://media.blazesi.com/highlights/lsu-hr.mp4',
        playerIds: ['h1'],
        tags: ['batting', 'power'],
        duration: 23,
      },
      {
        id: 'clip-tex-hr',
        type: 'video',
        title: 'Jace Jung lasers RBI double',
        description: '108 mph liner splits the gap and pushes xSLG to .587.',
        thumbnail: 'https://media.blazesi.com/thumbnails/tex-double.jpg',
        assetUrl: 'https://media.blazesi.com/highlights/tex-double.mp4',
        playerIds: ['p1'],
        tags: ['batting'],
        duration: 19,
      },
      {
        id: 'clip-lsu-k',
        type: 'video',
        title: 'Skenes climbs the ladder at 101',
        description: 'Stuff+ peaks at 136 on this high fastball.',
        thumbnail: 'https://media.blazesi.com/thumbnails/lsu-k.jpg',
        assetUrl: 'https://media.blazesi.com/highlights/lsu-k.mp4',
        playerIds: ['hp1'],
        tags: ['pitching'],
        duration: 17,
      },
      {
        id: 'clip-tex-k',
        type: 'video',
        title: 'Witt snaps off an 84 mph hammer',
        description: 'Pitch quality 83 with 19" vertical break.',
        thumbnail: 'https://media.blazesi.com/thumbnails/tex-k.jpg',
        assetUrl: 'https://media.blazesi.com/highlights/tex-k.mp4',
        playerIds: ['ap1'],
        tags: ['pitching'],
        duration: 21,
      },
      {
        id: 'clip-lsu-defense',
        type: 'video',
        title: 'Nippolt ranges deep in the hole',
        description: 'Diamond Pro defender range grade touches 87.',
        thumbnail: 'https://media.blazesi.com/thumbnails/lsu-defense.jpg',
        assetUrl: 'https://media.blazesi.com/highlights/lsu-defense.mp4',
        playerIds: ['h7', 'h9'],
        tags: ['defense'],
        duration: 25,
      },
      {
        id: 'clip-lsu-gap',
        type: 'image',
        title: 'Pearson spray chart',
        description: 'Spray distribution trend courtesy of Diamond Pro.',
        thumbnail: 'https://media.blazesi.com/thumbnails/lsu-spray.png',
        assetUrl: 'https://media.blazesi.com/visuals/lsu-spray.png',
        playerIds: ['h2'],
        tags: ['visual'],
        duration: null,
      },
    ],
    updatedAt: '2025-03-15T21:15:00Z',
  },
};

export const mockStandings = {
  conference: 'SEC',
  teams: [
    {
      id: 'lsu',
      name: 'LSU',
      confWins: 4,
      confLosses: 0,
      confPct: '.1000',
      overallWins: 15,
      overallLosses: 2,
      overallPct: '.882',
      homeWins: 8,
      homeLosses: 1,
      awayWins: 5,
      awayLosses: 1,
      rpiRank: 2,
      rpiValue: '.6845',
      streak: 'W8',
    },
    {
      id: 'florida',
      name: 'Florida',
      confWins: 3,
      confLosses: 0,
      confPct: '.1000',
      overallWins: 13,
      overallLosses: 3,
      overallPct: '.813',
      homeWins: 7,
      homeLosses: 2,
      awayWins: 4,
      awayLosses: 1,
      rpiRank: 5,
      rpiValue: '.6523',
      streak: 'W5',
    },
    {
      id: 'texas',
      name: 'Texas',
      confWins: 3,
      confLosses: 1,
      confPct: '.750',
      overallWins: 12,
      overallLosses: 3,
      overallPct: '.800',
      homeWins: 6,
      homeLosses: 1,
      awayWins: 4,
      awayLosses: 2,
      rpiRank: 8,
      rpiValue: '.6234',
      streak: 'W3',
    },
    {
      id: 'ole-miss',
      name: 'Ole Miss',
      confWins: 3,
      confLosses: 1,
      confPct: '.750',
      overallWins: 13,
      overallLosses: 4,
      overallPct: '.765',
      homeWins: 8,
      homeLosses: 2,
      awayWins: 3,
      awayLosses: 2,
      rpiRank: 11,
      rpiValue: '.5987',
      streak: 'W1',
    },
    {
      id: 'arkansas',
      name: 'Arkansas',
      confWins: 2,
      confLosses: 2,
      confPct: '.500',
      overallWins: 14,
      overallLosses: 4,
      overallPct: '.778',
      homeWins: 9,
      homeLosses: 1,
      awayWins: 3,
      awayLosses: 3,
      rpiRank: 7,
      rpiValue: '.6345',
      streak: 'L1',
    },
    {
      id: 'texas-am',
      name: 'Texas A&M',
      confWins: 2,
      confLosses: 1,
      confPct: '.667',
      overallWins: 11,
      overallLosses: 5,
      overallPct: '.688',
      homeWins: 7,
      homeLosses: 2,
      awayWins: 2,
      awayLosses: 3,
      rpiRank: 18,
      rpiValue: '.5654',
      streak: 'W2',
    },
    {
      id: 'vanderbilt',
      name: 'Vanderbilt',
      confWins: 1,
      confLosses: 2,
      confPct: '.333',
      overallWins: 10,
      overallLosses: 6,
      overallPct: '.625',
      homeWins: 6,
      homeLosses: 3,
      awayWins: 2,
      awayLosses: 3,
      rpiRank: 24,
      rpiValue: '.5423',
      streak: 'L2',
    },
    {
      id: 'mississippi-state',
      name: 'Mississippi State',
      confWins: 1,
      confLosses: 2,
      confPct: '.333',
      overallWins: 10,
      overallLosses: 6,
      overallPct: '.625',
      homeWins: 5,
      homeLosses: 3,
      awayWins: 3,
      awayLosses: 3,
      rpiRank: 29,
      rpiValue: '.5298',
      streak: 'L1',
    },
  ],
  leaders: {
    batting: [
      { name: 'Tommy White', team: 'LSU', avg: '.387' },
      { name: 'Jace Jung', team: 'Texas', avg: '.368' },
      { name: 'Josh Pearson', team: 'LSU', avg: '.351' },
    ],
    homeruns: [
      { name: 'Tommy White', team: 'LSU', hr: 8 },
      { name: 'Jace Jung', team: 'Texas', hr: 6 },
      { name: 'Wyatt Langford', team: 'Florida', hr: 6 },
    ],
    era: [
      { name: 'Paul Skenes', team: 'LSU', era: '1.69' },
      { name: 'Hagen Smith', team: 'Arkansas', era: '2.12' },
      { name: 'Hunter Barco', team: 'Florida', era: '2.45' },
    ],
    strikeouts: [
      { name: 'Paul Skenes', team: 'LSU', k: 52 },
      { name: 'Hagen Smith', team: 'Arkansas', k: 47 },
      { name: 'Hunter Barco', team: 'Florida', k: 43 },
    ],
  },
};
