// Mock data structures - represents what real NCAA/D1Baseball data would look like

export const mockLiveGames = [
  {
    id: 'game-001',
    status: 'live',
    date: '2025-03-15',
    scheduledTime: '2:00 PM CT',
    venue: 'Alex Box Stadium',
    inning: {
      number: 7,
      half: 'Top',
    },
    situation: {
      outs: 2,
      runners: 'Runners on 1st & 2nd',
    },
    awayTeam: {
      id: 'texas',
      name: 'Texas',
      abbreviation: 'TEX',
      conference: 'SEC',
      record: '12-3, 3-1 SEC',
      score: 4,
    },
    homeTeam: {
      id: 'lsu',
      name: 'LSU',
      abbreviation: 'LSU',
      conference: 'SEC',
      record: '15-2, 4-0 SEC',
      score: 6,
    },
    currentPitcher: {
      name: 'Javen Coleman',
      number: 17,
      pitches: 89,
      era: '3.24',
    },
    currentBatter: {
      name: 'Max Belyeu',
      number: 5,
      avg: '.342',
    },
    liveWinProbability: {
      summary: {
        current: {
          home: 0.68,
          away: 0.32,
        },
        lastUpdated: '2025-03-15T20:15:00Z',
      },
      timeline: [
        {
          pitchId: 'game-001-p1',
          inning: 7,
          half: 'Top',
          pitchCount: 1,
          batter: 'Max Belyeu',
          description: 'Coleman starts the AB with a painted fastball for strike one.',
          winProbability: { home: 0.64, away: 0.36 },
          leverageIndex: 1.78,
          pitchMeta: {
            pitchType: 'FF',
            velocity: 94.3,
            spinRate: 2245,
            zone: 'Up and in',
            release: { side: -1.8, height: 5.6, extension: 6.1 },
            plate: { x: -0.22, y: 0.48 },
          },
        },
        {
          pitchId: 'game-001-p2',
          inning: 7,
          half: 'Top',
          pitchCount: 2,
          batter: 'Max Belyeu',
          description: 'Changeup dives below the zone and Belyeu lays off.',
          winProbability: { home: 0.62, away: 0.38 },
          leverageIndex: 1.74,
          pitchMeta: {
            pitchType: 'CH',
            velocity: 83.9,
            spinRate: 1798,
            zone: 'Below',
            release: { side: -1.6, height: 5.4, extension: 6.0 },
            plate: { x: -0.1, y: -0.25 },
          },
        },
        {
          pitchId: 'game-001-p3',
          inning: 7,
          half: 'Top',
          pitchCount: 3,
          batter: 'Max Belyeu',
          description: 'Slider sweeps across the plate for strike two.',
          winProbability: { home: 0.69, away: 0.31 },
          leverageIndex: 1.82,
          pitchMeta: {
            pitchType: 'SL',
            velocity: 85.6,
            spinRate: 2480,
            zone: 'Outer edge',
            release: { side: -2.05, height: 5.45, extension: 5.9 },
            plate: { x: 0.38, y: 0.35 },
          },
          isKeyEvent: true,
        },
        {
          pitchId: 'game-001-p4',
          inning: 7,
          half: 'Top',
          pitchCount: 4,
          batter: 'Max Belyeu',
          description: 'Four-seamer misses arm side to even the count.',
          winProbability: { home: 0.66, away: 0.34 },
          leverageIndex: 1.65,
          pitchMeta: {
            pitchType: 'FF',
            velocity: 95.1,
            spinRate: 2262,
            zone: 'Arm side miss',
            release: { side: -1.75, height: 5.5, extension: 6.2 },
            plate: { x: -0.65, y: 1.35 },
          },
        },
        {
          pitchId: 'game-001-p5',
          inning: 7,
          half: 'Top',
          pitchCount: 5,
          batter: 'Max Belyeu',
          description: 'Belyeu fouls off a tough fastball to stay alive.',
          winProbability: { home: 0.67, away: 0.33 },
          leverageIndex: 1.72,
          pitchMeta: {
            pitchType: 'FF',
            velocity: 95.6,
            spinRate: 2285,
            zone: 'Top rail',
            release: { side: -1.85, height: 5.65, extension: 6.3 },
            plate: { x: -0.05, y: 0.95 },
          },
        },
        {
          pitchId: 'game-001-p6',
          inning: 7,
          half: 'Top',
          pitchCount: 6,
          batter: 'Max Belyeu',
          description: 'Coleman finishes the AB with a front-door slider and picks up strike three.',
          winProbability: { home: 0.74, away: 0.26 },
          leverageIndex: 2.03,
          pitchMeta: {
            pitchType: 'SL',
            velocity: 85.2,
            spinRate: 2510,
            zone: 'Front door',
            release: { side: -2.1, height: 5.35, extension: 5.95 },
            plate: { x: -0.12, y: 0.2 },
          },
          isKeyEvent: true,
        },
      ],
      pitchTracking: {
        releasePoints: [
          { pitchId: 'game-001-p1', side: -1.8, height: 5.6, extension: 6.1, pitchType: 'FF', velocity: 94.3 },
          { pitchId: 'game-001-p2', side: -1.6, height: 5.4, extension: 6.0, pitchType: 'CH', velocity: 83.9 },
          { pitchId: 'game-001-p3', side: -2.05, height: 5.45, extension: 5.9, pitchType: 'SL', velocity: 85.6 },
          { pitchId: 'game-001-p4', side: -1.75, height: 5.5, extension: 6.2, pitchType: 'FF', velocity: 95.1 },
          { pitchId: 'game-001-p5', side: -1.85, height: 5.65, extension: 6.3, pitchType: 'FF', velocity: 95.6 },
          { pitchId: 'game-001-p6', side: -2.1, height: 5.35, extension: 5.95, pitchType: 'SL', velocity: 85.2 },
        ],
        plateLocations: [
          { pitchId: 'game-001-p1', x: -0.22, y: 0.48, outcome: 'Called Strike', pitchType: 'FF' },
          { pitchId: 'game-001-p2', x: -0.1, y: -0.25, outcome: 'Ball', pitchType: 'CH' },
          { pitchId: 'game-001-p3', x: 0.38, y: 0.35, outcome: 'Called Strike', pitchType: 'SL' },
          { pitchId: 'game-001-p4', x: -0.65, y: 1.35, outcome: 'Ball', pitchType: 'FF' },
          { pitchId: 'game-001-p5', x: -0.05, y: 0.95, outcome: 'Foul', pitchType: 'FF' },
          { pitchId: 'game-001-p6', x: -0.12, y: 0.2, outcome: 'Strikeout', pitchType: 'SL' },
        ],
      },
    },
  },
  {
    id: 'game-002',
    status: 'live',
    date: '2025-03-15',
    scheduledTime: '3:00 PM CT',
    venue: 'Blue Bell Park',
    inning: {
      number: 5,
      half: 'Bottom',
    },
    situation: {
      outs: 1,
      runners: 'Runner on 3rd',
    },
    awayTeam: {
      id: 'arkansas',
      name: 'Arkansas',
      abbreviation: 'ARK',
      conference: 'SEC',
      record: '14-4, 2-2 SEC',
      score: 3,
    },
    homeTeam: {
      id: 'texas-am',
      name: 'Texas A&M',
      abbreviation: 'TAMU',
      conference: 'SEC',
      record: '11-5, 2-1 SEC',
      score: 5,
    },
    currentPitcher: {
      name: 'Will McEntire',
      number: 30,
      pitches: 67,
      era: '2.87',
    },
    currentBatter: {
      name: 'Kaeden Kent',
      number: 13,
      avg: '.298',
    },
    liveWinProbability: {
      summary: {
        current: {
          home: 0.61,
          away: 0.39,
        },
        lastUpdated: '2025-03-15T19:40:00Z',
      },
      timeline: [
        {
          pitchId: 'game-002-p1',
          inning: 5,
          half: 'Bottom',
          pitchCount: 1,
          batter: 'Kaeden Kent',
          description: 'McEntire gets ahead with a first-pitch curve for a called strike.',
          winProbability: { home: 0.58, away: 0.42 },
          leverageIndex: 1.38,
          pitchMeta: {
            pitchType: 'CB',
            velocity: 79.4,
            spinRate: 2555,
            zone: 'Glove side low',
            release: { side: -2.25, height: 5.7, extension: 5.7 },
            plate: { x: 0.32, y: 0.15 },
          },
        },
        {
          pitchId: 'game-002-p2',
          inning: 5,
          half: 'Bottom',
          pitchCount: 2,
          batter: 'Kaeden Kent',
          description: 'Fastball just misses up to even the count.',
          winProbability: { home: 0.57, away: 0.43 },
          leverageIndex: 1.35,
          pitchMeta: {
            pitchType: 'FF',
            velocity: 93.8,
            spinRate: 2310,
            zone: 'Above zone',
            release: { side: -2.05, height: 5.65, extension: 6.05 },
            plate: { x: -0.12, y: 1.25 },
          },
        },
        {
          pitchId: 'game-002-p3',
          inning: 5,
          half: 'Bottom',
          pitchCount: 3,
          batter: 'Kaeden Kent',
          description: 'Kent turns on a hanging slider for a line-drive double to right.',
          winProbability: { home: 0.71, away: 0.29 },
          leverageIndex: 1.92,
          pitchMeta: {
            pitchType: 'SL',
            velocity: 84.1,
            spinRate: 2415,
            zone: 'Middle in',
            release: { side: -2.15, height: 5.55, extension: 5.85 },
            plate: { x: -0.45, y: 0.52 },
          },
          isKeyEvent: true,
        },
        {
          pitchId: 'game-002-p4',
          inning: 5,
          half: 'Bottom',
          pitchCount: 4,
          batter: 'Braden Montgomery',
          description: 'Slider in the dirt moves the runner to third base.',
          winProbability: { home: 0.69, away: 0.31 },
          leverageIndex: 1.85,
          pitchMeta: {
            pitchType: 'SL',
            velocity: 84.6,
            spinRate: 2460,
            zone: 'Dirt',
            release: { side: -2.18, height: 5.5, extension: 5.8 },
            plate: { x: 0.05, y: -0.35 },
          },
        },
        {
          pitchId: 'game-002-p5',
          inning: 5,
          half: 'Bottom',
          pitchCount: 5,
          batter: 'Braden Montgomery',
          description: 'Montgomery lifts a sac fly to center, extending the Aggies lead.',
          winProbability: { home: 0.78, away: 0.22 },
          leverageIndex: 2.05,
          pitchMeta: {
            pitchType: 'FF',
            velocity: 94.6,
            spinRate: 2338,
            zone: 'Middle',
            release: { side: -2.1, height: 5.6, extension: 6.1 },
            plate: { x: -0.02, y: 0.4 },
          },
          isKeyEvent: true,
        },
      ],
      pitchTracking: {
        releasePoints: [
          { pitchId: 'game-002-p1', side: -2.25, height: 5.7, extension: 5.7, pitchType: 'CB', velocity: 79.4 },
          { pitchId: 'game-002-p2', side: -2.05, height: 5.65, extension: 6.05, pitchType: 'FF', velocity: 93.8 },
          { pitchId: 'game-002-p3', side: -2.15, height: 5.55, extension: 5.85, pitchType: 'SL', velocity: 84.1 },
          { pitchId: 'game-002-p4', side: -2.18, height: 5.5, extension: 5.8, pitchType: 'SL', velocity: 84.6 },
          { pitchId: 'game-002-p5', side: -2.1, height: 5.6, extension: 6.1, pitchType: 'FF', velocity: 94.6 },
        ],
        plateLocations: [
          { pitchId: 'game-002-p1', x: 0.32, y: 0.15, outcome: 'Called Strike', pitchType: 'CB' },
          { pitchId: 'game-002-p2', x: -0.12, y: 1.25, outcome: 'Ball', pitchType: 'FF' },
          { pitchId: 'game-002-p3', x: -0.45, y: 0.52, outcome: 'Double', pitchType: 'SL' },
          { pitchId: 'game-002-p4', x: 0.05, y: -0.35, outcome: 'Wild Pitch', pitchType: 'SL' },
          { pitchId: 'game-002-p5', x: -0.02, y: 0.4, outcome: 'Sac Fly', pitchType: 'FF' },
        ],
      },
    },
  },
  {
    id: 'game-003',
    status: 'final',
    date: '2025-03-15',
    scheduledTime: '12:00 PM CT',
    venue: 'Swayze Field',
    awayTeam: {
      id: 'mississippi-state',
      name: 'Mississippi State',
      abbreviation: 'MSU',
      conference: 'SEC',
      record: '10-6, 1-2 SEC',
      score: 2,
    },
    homeTeam: {
      id: 'ole-miss',
      name: 'Ole Miss',
      abbreviation: 'OM',
      conference: 'SEC',
      record: '13-4, 3-1 SEC',
      score: 7,
    },
  },
];

export const mockBoxScore = {
  lineScore: {
    innings: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    away: {
      innings: [0, 2, 0, 1, 0, 0, 1, 0, 0],
      runs: 4,
      hits: 8,
      errors: 1,
    },
    home: {
      innings: [1, 0, 2, 0, 1, 2, 0, 0, null],
      runs: 6,
      hits: 10,
      errors: 0,
    },
  },
  batting: {
    away: [
      {
        id: 'p1',
        name: 'Jace Jung',
        position: 'SS',
        ab: 4,
        r: 1,
        h: 2,
        rbi: 1,
        bb: 0,
        k: 1,
        seasonAvg: '.368',
      },
      {
        id: 'p2',
        name: 'Max Belyeu',
        position: 'LF',
        ab: 4,
        r: 1,
        h: 1,
        rbi: 0,
        bb: 1,
        k: 2,
        seasonAvg: '.342',
      },
      {
        id: 'p3',
        name: 'Eric Kennedy',
        position: 'RF',
        ab: 4,
        r: 0,
        h: 2,
        rbi: 2,
        bb: 0,
        k: 0,
        seasonAvg: '.315',
      },
      {
        id: 'p4',
        name: 'Will Gasparino',
        position: '1B',
        ab: 3,
        r: 1,
        h: 1,
        rbi: 0,
        bb: 1,
        k: 1,
        seasonAvg: '.287',
      },
      {
        id: 'p5',
        name: 'Jordan Thompson',
        position: 'C',
        ab: 4,
        r: 0,
        h: 1,
        rbi: 0,
        bb: 0,
        k: 2,
        seasonAvg: '.294',
      },
      {
        id: 'p6',
        name: 'Jack ODowd',
        position: '2B',
        ab: 3,
        r: 1,
        h: 1,
        rbi: 1,
        bb: 0,
        k: 0,
        seasonAvg: '.276',
      },
      {
        id: 'p7',
        name: 'Kimble Schuessler',
        position: '3B',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 1,
        seasonAvg: '.248',
      },
      {
        id: 'p8',
        name: 'Mitchell Daly',
        position: 'DH',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 2,
        seasonAvg: '.221',
      },
      {
        id: 'p9',
        name: 'Peyton Graham',
        position: 'CF',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 1,
        seasonAvg: '.267',
      },
    ],
    home: [
      {
        id: 'h1',
        name: 'Tommy White',
        position: '1B',
        ab: 4,
        r: 2,
        h: 3,
        rbi: 2,
        bb: 0,
        k: 0,
        seasonAvg: '.387',
      },
      {
        id: 'h2',
        name: 'Josh Pearson',
        position: 'RF',
        ab: 4,
        r: 1,
        h: 2,
        rbi: 1,
        bb: 0,
        k: 1,
        seasonAvg: '.351',
      },
      {
        id: 'h3',
        name: 'Jared Jones',
        position: 'LF',
        ab: 4,
        r: 1,
        h: 2,
        rbi: 2,
        bb: 0,
        k: 0,
        seasonAvg: '.329',
      },
      {
        id: 'h4',
        name: 'Alex Milmartineau',
        position: 'C',
        ab: 3,
        r: 1,
        h: 1,
        rbi: 0,
        bb: 1,
        k: 0,
        seasonAvg: '.298',
      },
      {
        id: 'h5',
        name: 'Michael Braswell III',
        position: '3B',
        ab: 3,
        r: 0,
        h: 1,
        rbi: 1,
        bb: 0,
        k: 1,
        seasonAvg: '.312',
      },
      {
        id: 'h6',
        name: 'Hayden Travinski',
        position: '2B',
        ab: 3,
        r: 1,
        h: 1,
        rbi: 0,
        bb: 1,
        k: 0,
        seasonAvg: '.276',
      },
      {
        id: 'h7',
        name: 'Ben Nippolt',
        position: 'SS',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 2,
        seasonAvg: '.254',
      },
      {
        id: 'h8',
        name: 'Ethan Frey',
        position: 'DH',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 1,
        seasonAvg: '.239',
      },
      {
        id: 'h9',
        name: 'Josh Stevenson',
        position: 'CF',
        ab: 3,
        r: 0,
        h: 0,
        rbi: 0,
        bb: 0,
        k: 1,
        seasonAvg: '.265',
      },
    ],
  },
  pitching: {
    away: [
      {
        id: 'ap1',
        name: 'Tanner Witt',
        ip: '4.0',
        h: 6,
        r: 4,
        er: 4,
        bb: 2,
        k: 4,
        pitches: 78,
        seasonEra: '3.45',
      },
      {
        id: 'ap2',
        name: 'Andre Duplantier II',
        ip: '2.0',
        h: 3,
        r: 2,
        er: 2,
        bb: 1,
        k: 2,
        pitches: 38,
        seasonEra: '4.12',
      },
      {
        id: 'ap3',
        name: 'Cam Caley',
        ip: '0.2',
        h: 1,
        r: 0,
        er: 0,
        bb: 0,
        k: 1,
        pitches: 12,
        decision: 'L (2-1)',
        seasonEra: '2.87',
      },
    ],
    home: [
      {
        id: 'hp1',
        name: 'Paul Skenes',
        ip: '6.0',
        h: 5,
        r: 3,
        er: 3,
        bb: 1,
        k: 9,
        pitches: 94,
        decision: 'W (4-0)',
        seasonEra: '1.69',
      },
      {
        id: 'hp2',
        name: 'Javen Coleman',
        ip: '1.0',
        h: 2,
        r: 1,
        er: 1,
        bb: 0,
        k: 1,
        pitches: 18,
        seasonEra: '3.24',
      },
      {
        id: 'hp3',
        name: 'Garrett Edwards',
        ip: '2.0',
        h: 1,
        r: 0,
        er: 0,
        bb: 0,
        k: 3,
        pitches: 24,
        decision: 'SV (5)',
        seasonEra: '1.98',
      },
    ],
  },
};

export const mockStandings = {
  conference: 'SEC',
  teams: [
    {
      id: 'lsu',
      name: 'LSU',
      confWins: 4,
      confLosses: 0,
      confPct: '.1000',
      overallWins: 15,
      overallLosses: 2,
      overallPct: '.882',
      homeWins: 8,
      homeLosses: 1,
      awayWins: 5,
      awayLosses: 1,
      rpiRank: 2,
      rpiValue: '.6845',
      streak: 'W8',
    },
    {
      id: 'florida',
      name: 'Florida',
      confWins: 3,
      confLosses: 0,
      confPct: '.1000',
      overallWins: 13,
      overallLosses: 3,
      overallPct: '.813',
      homeWins: 7,
      homeLosses: 2,
      awayWins: 4,
      awayLosses: 1,
      rpiRank: 5,
      rpiValue: '.6523',
      streak: 'W5',
    },
    {
      id: 'texas',
      name: 'Texas',
      confWins: 3,
      confLosses: 1,
      confPct: '.750',
      overallWins: 12,
      overallLosses: 3,
      overallPct: '.800',
      homeWins: 6,
      homeLosses: 1,
      awayWins: 4,
      awayLosses: 2,
      rpiRank: 8,
      rpiValue: '.6234',
      streak: 'W3',
    },
    {
      id: 'ole-miss',
      name: 'Ole Miss',
      confWins: 3,
      confLosses: 1,
      confPct: '.750',
      overallWins: 13,
      overallLosses: 4,
      overallPct: '.765',
      homeWins: 8,
      homeLosses: 2,
      awayWins: 3,
      awayLosses: 2,
      rpiRank: 11,
      rpiValue: '.5987',
      streak: 'W1',
    },
    {
      id: 'arkansas',
      name: 'Arkansas',
      confWins: 2,
      confLosses: 2,
      confPct: '.500',
      overallWins: 14,
      overallLosses: 4,
      overallPct: '.778',
      homeWins: 9,
      homeLosses: 1,
      awayWins: 3,
      awayLosses: 3,
      rpiRank: 7,
      rpiValue: '.6345',
      streak: 'L1',
    },
    {
      id: 'texas-am',
      name: 'Texas A&M',
      confWins: 2,
      confLosses: 1,
      confPct: '.667',
      overallWins: 11,
      overallLosses: 5,
      overallPct: '.688',
      homeWins: 7,
      homeLosses: 2,
      awayWins: 2,
      awayLosses: 3,
      rpiRank: 18,
      rpiValue: '.5654',
      streak: 'W2',
    },
    {
      id: 'vanderbilt',
      name: 'Vanderbilt',
      confWins: 1,
      confLosses: 2,
      confPct: '.333',
      overallWins: 10,
      overallLosses: 6,
      overallPct: '.625',
      homeWins: 6,
      homeLosses: 3,
      awayWins: 2,
      awayLosses: 3,
      rpiRank: 24,
      rpiValue: '.5423',
      streak: 'L2',
    },
    {
      id: 'mississippi-state',
      name: 'Mississippi State',
      confWins: 1,
      confLosses: 2,
      confPct: '.333',
      overallWins: 10,
      overallLosses: 6,
      overallPct: '.625',
      homeWins: 5,
      homeLosses: 3,
      awayWins: 3,
      awayLosses: 3,
      rpiRank: 29,
      rpiValue: '.5298',
      streak: 'L1',
    },
  ],
  leaders: {
    batting: [
      { name: 'Tommy White', team: 'LSU', avg: '.387' },
      { name: 'Jace Jung', team: 'Texas', avg: '.368' },
      { name: 'Josh Pearson', team: 'LSU', avg: '.351' },
    ],
    homeruns: [
      { name: 'Tommy White', team: 'LSU', hr: 8 },
      { name: 'Jace Jung', team: 'Texas', hr: 6 },
      { name: 'Wyatt Langford', team: 'Florida', hr: 6 },
    ],
    era: [
      { name: 'Paul Skenes', team: 'LSU', era: '1.69' },
      { name: 'Hagen Smith', team: 'Arkansas', era: '2.12' },
      { name: 'Hunter Barco', team: 'Florida', era: '2.45' },
    ],
    strikeouts: [
      { name: 'Paul Skenes', team: 'LSU', k: 52 },
      { name: 'Hagen Smith', team: 'Arkansas', k: 47 },
      { name: 'Hunter Barco', team: 'Florida', k: 43 },
    ],
  },
};
