name = "blazesportsintel"
pages_build_output_dir = "out"
compatibility_date = "2025-03-07"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "BSI_CACHE"
id = "e6cb68e815cd45babeee0e10460dbfee"

[[kv_namespaces]]
binding = "BSI_FANBASE_CACHE"
id = "e6cb68e815cd45babeee0e10460dbfee"

[[kv_namespaces]]
binding = "KV"
id = "e6cb68e815cd45babeee0e10460dbfee"

[[kv_namespaces]]
binding = "NIL_CACHE"
id = "e6cb68e815cd45babeee0e10460dbfee"

[[kv_namespaces]]
binding = "BSI_PROD_CACHE"
id = "e6cb68e815cd45babeee0e10460dbfee"

[[kv_namespaces]]
binding = "BSI_SPORTRADAR_CACHE"
id = "5763d0076cb744ed9c629b9042a61033"

[[d1_databases]]
database_id = "9cecff0f-a3ab-433f-bf10-d2664d9542b0"
binding = "DB"
database_name = "DB"

[[d1_databases]]
database_id = "955e3dc2-4ea1-4b46-8464-0340f1cf3fc5"
binding = "FANBASE_DB"
database_name = "FANBASE_DB"

[[d1_databases]]
database_id = "88eb676f-af0f-470c-a46a-b9429f5b51f3"
binding = "GAME_DB"
database_name = "GAME_DB"

[[d1_databases]]
database_id = "9cecff0f-a3ab-433f-bf10-d2664d9542b0"
binding = "NIL_DB"
database_name = "NIL_DB"

[[r2_buckets]]
bucket_name = "blaze-nil-archive"
binding = "NIL_ARCHIVE"

[[r2_buckets]]
bucket_name = "blaze-sports-data-lake"
binding = "SPORTS_DATA"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "bsi_sports_metrics"

[ai]
binding = "AI"

[env.production.vars]
ENVIRONMENT = "production"
NEXT_PUBLIC_POSTHOG_KEY = "phc_KirkHATYxmVzlCgyZzXRwpdTvrKBVA4vyZ7b44NTtE5"

[[env.production.kv_namespaces]]
binding = "BSI_CACHE"
id = "e6cb68e815cd45babeee0e10460dbfee"

[[env.production.kv_namespaces]]
binding = "BSI_FANBASE_CACHE"
id = "e6cb68e815cd45babeee0e10460dbfee"

[[env.production.kv_namespaces]]
binding = "KV"
id = "e6cb68e815cd45babeee0e10460dbfee"

[[env.production.kv_namespaces]]
binding = "NIL_CACHE"
id = "e6cb68e815cd45babeee0e10460dbfee"

[[env.production.kv_namespaces]]
binding = "BSI_PROD_CACHE"
id = "e6cb68e815cd45babeee0e10460dbfee"

[[env.production.kv_namespaces]]
binding = "BSI_SPORTRADAR_CACHE"
id = "5763d0076cb744ed9c629b9042a61033"

[[env.production.d1_databases]]
database_id = "9cecff0f-a3ab-433f-bf10-d2664d9542b0"
binding = "DB"
database_name = "DB"

[[env.production.d1_databases]]
database_id = "955e3dc2-4ea1-4b46-8464-0340f1cf3fc5"
binding = "FANBASE_DB"
database_name = "FANBASE_DB"

[[env.production.d1_databases]]
database_id = "88eb676f-af0f-470c-a46a-b9429f5b51f3"
binding = "GAME_DB"
database_name = "GAME_DB"

[[env.production.d1_databases]]
database_id = "9cecff0f-a3ab-433f-bf10-d2664d9542b0"
binding = "NIL_DB"
database_name = "NIL_DB"

[[env.production.r2_buckets]]
bucket_name = "blaze-nil-archive"
binding = "NIL_ARCHIVE"

[[env.production.r2_buckets]]
bucket_name = "blaze-sports-data-lake"
binding = "SPORTS_DATA"

[[env.production.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "bsi_sports_metrics"

[env.production.ai]
binding = "AI"
