/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime --config workers/error-tracker/wrangler.toml workers/error-tracker/env.d.ts` (hash: cc7bc49f2cef4856247a42af413ed240)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		ERROR_LOG: KVNamespace;
	}
}
interface Env extends Cloudflare.Env {}
