/**
 * BSI Error Tracker — Tail Worker
 *
 * Consumes logs from BSI workers via Cloudflare Tail Workers.
 * Filters for errors and exceptions, stores individual entries AND
 * fingerprint-based cluster summaries in KV.
 *
 * Architecture:
 *   Any BSI worker → [tail] → bsi-error-tracker → KV (BSI_ERROR_LOG)
 *
 * To attach this worker as a tail consumer, add to the producer's wrangler.toml:
 *   [[tail_consumers]]
 *   service = "bsi-error-tracker"
 *
 * Key patterns:
 *   err:{date}:{ts}:{rand}           — individual error (7-day TTL)
 *   err-cluster:{fingerprint}        — rolling cluster summary (24h TTL)
 *   err-clusters:index               — list of active cluster fingerprints (24h TTL)
 *
 * Query:
 *   wrangler kv get --namespace-id=<ID> "err-clusters:index"
 *   wrangler kv get --namespace-id=<ID> "err-cluster:<fingerprint>"
 */

// Env generated by wrangler types → env.d.ts + env.secrets.d.ts

// TraceItem, TraceLog, TraceException provided by @cloudflare/workers-types

const SEVEN_DAYS = 7 * 24 * 60 * 60;
const TWENTY_FOUR_HOURS = 24 * 60 * 60;

interface ErrorCluster {
  fingerprint: string;
  worker: string;
  kind: string;        // 'exception' | 'log_error' | 'bad_outcome'
  message: string;     // normalized pattern (first occurrence)
  count: number;
  firstSeen: string;
  lastSeen: string;
  sample: string;      // most recent raw message
}

function generateKey(): string {
  const now = new Date();
  const datePrefix = now.toISOString().slice(0, 10);
  const ts = now.getTime();
  const rand = Math.random().toString(36).slice(2, 8);
  return `err:${datePrefix}:${ts}:${rand}`;
}

/**
 * Build a fingerprint from worker + error type + normalized message.
 * Strips numbers, UUIDs, and timestamps to group similar errors together.
 */
function fingerprint(worker: string, kind: string, message: string): string {
  const normalized = message
    .replace(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi, '{uuid}')
    .replace(/\d{4}-\d{2}-\d{2}T[\d:.]+Z?/g, '{ts}')
    .replace(/\d{10,13}/g, '{n}')
    .replace(/:\d+/g, ':{n}')
    .slice(0, 120);
  // Simple hash — doesn't need to be cryptographic, just deterministic
  let hash = 0;
  const str = `${worker}:${kind}:${normalized}`;
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) - hash + str.charCodeAt(i)) | 0;
  }
  return (hash >>> 0).toString(36);
}

export default {
  async tail(events: TraceItem[], env: Env): Promise<void> {
    const errors: Array<Record<string, unknown>> = [];

    for (const event of events) {
      const reqInfo = event.event && 'request' in event.event ? event.event.request : null;
      const requestUrl = reqInfo?.url ?? 'unknown';
      const requestMethod = reqInfo?.method ?? 'unknown';
      const worker = event.scriptName ?? 'unknown';

      // Capture uncaught exceptions
      for (const exception of event.exceptions) {
        errors.push({
          type: 'exception',
          worker,
          name: exception.name,
          message: exception.message,
          timestamp: new Date(exception.timestamp).toISOString(),
          requestUrl,
          requestMethod,
          outcome: event.outcome,
        });
      }

      // Capture error-level log lines
      for (const log of event.logs) {
        if (log.level !== 'error') continue;

        let parsed: Record<string, unknown> | null = null;
        try {
          if (log.message.length === 1 && log.message[0].startsWith('{')) {
            parsed = JSON.parse(log.message[0]);
          }
        } catch (err) {
          console.error('[error-tracker] JSON parse failed:', err instanceof Error ? err.message : err);
        }

        errors.push({
          type: 'log_error',
          worker,
          ...(parsed ?? { message: log.message.join(' ') }),
          logTimestamp: new Date(log.timestamp).toISOString(),
          requestUrl,
          requestMethod,
          outcome: event.outcome,
        });
      }

      // Capture non-OK outcomes (e.g., exceededCpu, exceededMemory, scriptNotFound)
      if (event.outcome !== 'ok' && event.outcome !== 'canceled') {
        errors.push({
          type: 'bad_outcome',
          worker,
          outcome: event.outcome,
          message: `Worker outcome: ${event.outcome}`,
          timestamp: event.eventTimestamp
            ? new Date(event.eventTimestamp).toISOString()
            : new Date().toISOString(),
          requestUrl,
          requestMethod,
        });
      }
    }

    if (errors.length === 0) return;

    // ── Individual error writes (preserves raw log for debugging) ──
    const rawWrites = errors.map((error) =>
      env.ERROR_LOG.put(generateKey(), JSON.stringify(error), {
        expirationTtl: SEVEN_DAYS,
      }),
    );

    // ── Cluster aggregation ──
    // Group this batch by fingerprint
    const batchClusters = new Map<string, {
      worker: string;
      kind: string;
      message: string;
      count: number;
      latestMessage: string;
      latestTimestamp: string;
    }>();

    for (const error of errors) {
      const w = String(error.worker ?? 'unknown');
      const k = String(error.type ?? 'error');
      const m = String(error.message ?? error.name ?? 'Unknown error');
      const fp = fingerprint(w, k, m);

      const existing = batchClusters.get(fp);
      if (existing) {
        existing.count++;
        existing.latestMessage = m;
        existing.latestTimestamp = String(error.timestamp ?? error.logTimestamp ?? new Date().toISOString());
      } else {
        batchClusters.set(fp, {
          worker: w,
          kind: k,
          message: m,
          count: 1,
          latestMessage: m,
          latestTimestamp: String(error.timestamp ?? error.logTimestamp ?? new Date().toISOString()),
        });
      }
    }

    // Read existing clusters and merge
    const clusterWrites: Promise<void>[] = [];
    const activeFingerprints = new Set<string>();

    // Read existing cluster index to preserve fingerprints from prior batches
    let existingIndex: string[] = [];
    try {
      const raw = await env.ERROR_LOG.get('err-clusters:index', 'text');
      if (raw) existingIndex = JSON.parse(raw) as string[];
    } catch { /* first run or corrupt — start fresh */ }

    for (const fp of existingIndex) activeFingerprints.add(fp);

    for (const [fp, batch] of batchClusters) {
      activeFingerprints.add(fp);

      // Read existing cluster (if any) and merge
      let cluster: ErrorCluster;
      try {
        const raw = await env.ERROR_LOG.get(`err-cluster:${fp}`, 'text');
        if (raw) {
          const existing = JSON.parse(raw) as ErrorCluster;
          existing.count += batch.count;
          existing.lastSeen = batch.latestTimestamp;
          existing.sample = batch.latestMessage;
          cluster = existing;
        } else {
          cluster = {
            fingerprint: fp,
            worker: batch.worker,
            kind: batch.kind,
            message: batch.message,
            count: batch.count,
            firstSeen: batch.latestTimestamp,
            lastSeen: batch.latestTimestamp,
            sample: batch.latestMessage,
          };
        }
      } catch {
        cluster = {
          fingerprint: fp,
          worker: batch.worker,
          kind: batch.kind,
          message: batch.message,
          count: batch.count,
          firstSeen: batch.latestTimestamp,
          lastSeen: batch.latestTimestamp,
          sample: batch.latestMessage,
        };
      }

      clusterWrites.push(
        env.ERROR_LOG.put(`err-cluster:${fp}`, JSON.stringify(cluster), {
          expirationTtl: TWENTY_FOUR_HOURS,
        }),
      );
    }

    // Write updated index (capped at 100 fingerprints)
    const indexArr = [...activeFingerprints].slice(0, 100);
    clusterWrites.push(
      env.ERROR_LOG.put('err-clusters:index', JSON.stringify(indexArr), {
        expirationTtl: TWENTY_FOUR_HOURS,
      }),
    );

    await Promise.all([...rawWrites, ...clusterWrites]);

    // Optional: send webhook alert for critical errors
    if (env.ALERT_WEBHOOK_URL) {
      const summary = `${errors.length} error(s) from ${[...new Set(errors.map(e => e.worker))].join(', ')}`;
      try {
        await fetch(env.ALERT_WEBHOOK_URL, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            content: `[BSI Error Tracker] ${summary}`,
            errors: errors.slice(0, 5),
          }),
        });
      } catch (err) {
        console.error('[error-tracker] Alert webhook failed:', err instanceof Error ? err.message : err);
      }
    }
  },
} satisfies ExportedHandler<Env>;
