name = "bsi-qc-worker"
main = "index.ts"
compatibility_date = "2025-03-01"
node_compat = true

# Routes - Deploy to qc subdomain
routes = [
  { pattern = "qc.blazesportsintel.com/*", zone_name = "blazesportsintel.com" }
]

# KV Namespace for QC reports
[[kv_namespaces]]
binding = "CACHE"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID"

# R2 Bucket for report archival
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "bsi-qc-reports"
preview_bucket_name = "bsi-qc-reports-preview"

# Analytics Engine
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# Environment Variables
[vars]
# Add non-sensitive variables here

# Secrets (set via: wrangler secret put QC_API_SECRET)
# QC_API_SECRET = "your-secret-key"

# Scheduled Jobs
[triggers]
crons = ["0 3 * * *"]  # Daily at 3am UTC

# Build Configuration
[build]
command = ""

# Deployment
[env.production]
name = "bsi-qc-worker"
routes = [
  { pattern = "qc.blazesportsintel.com/*", zone_name = "blazesportsintel.com" }
]

[env.staging]
name = "bsi-qc-worker-staging"
routes = [
  { pattern = "qc-staging.blazesportsintel.com/*", zone_name = "blazesportsintel.com" }
]
