name = "bsi-qc-worker"
main = "index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

# KV Namespace for QC reports (using existing CACHE namespace)
[[kv_namespaces]]
binding = "CACHE"
id = "a53c3726fc3044be82e79d2d1e371d26"

# R2 Bucket for report archival
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "bsi-qc-reports"

# Analytics Engine
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# Environment Variables
[vars]
# Add non-sensitive variables here

# Secrets (set via: wrangler secret put QC_API_SECRET)
# QC_API_SECRET = "your-secret-key"

# Scheduled Jobs
[triggers]
crons = ["0 3 * * *"]  # Daily at 3am UTC

# Build Configuration
[build]
command = ""

# Deployment environments removed for initial deployment
# Will deploy to workers.dev subdomain first
