/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime --config workers/sportradar-ingest/wrangler.toml workers/sportradar-ingest/env.d.ts` (hash: 2f0dfa76fe9973998f3354173e489c86)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		KV: KVNamespace;
		R2: R2Bucket;
		DB: D1Database;
	}
}
interface Env extends Cloudflare.Env {}
