# Cloudflare Workers Configuration - Live Game Win Probability Simulation
# Purpose: Real-time Monte Carlo simulation for in-game win probability
# Deployment: wrangler deploy (from workers/live-sim/)

name = "blazesports-live-sim"
compatibility_date = "2025-01-01"
main = "src/index.ts"

# Worker Type
workers_dev = true

# Routes (set after deployment)
# routes = [
#   { pattern = "live.blazesportsintel.com/*", zone_name = "blazesportsintel.com" }
# ]

# Environment Variables
[vars]
# Set via wrangler secret put:
# INGEST_SECRET = ""

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "live-sim"
database_id = "" # Set after creating: wrangler d1 create live-sim

# KV Namespace (Cache)
[[kv_namespaces]]
binding = "CACHE"
id = "" # Set after creating: wrangler kv:namespace create CACHE
preview_id = "" # Set after creating: wrangler kv:namespace create CACHE --preview

# R2 Bucket (Optional - for reference data like park factors)
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "blazesports-live-sim-data"

# Analytics Engine
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "bsi_live_sim_analytics"

# Durable Objects
[[durable_objects.bindings]]
name = "GAME_COORDINATOR"
class_name = "GameCoordinator"
script_name = "blazesports-live-sim"

[[migrations]]
tag = "v1"
new_classes = ["GameCoordinator"]

# Build Configuration
[build]
command = "npm run build"

# Static Assets (serve dashboard)
[site]
bucket = "./public"

# Compatibility Flags
compatibility_flags = ["nodejs_compat"]

# Limits
[limits]
cpu_ms = 50 # Increased for Monte Carlo simulation

# Development
[dev]
port = 8788
local_protocol = "http"
