# Blaze Intelligence Data Drift Monitoring Configuration
# The Deep South's Sports Intelligence Hub
# Last Updated: 2025-09-26

monitoring:
  enabled: true
  environment: production
  timezone: America/Chicago

datasets:
  # MLB Real-time Feeds
  mlb_stats:
    name: "MLB Cardinals Analytics"
    source: "api/cardinals-readiness"
    type: streaming
    schema_version: "2.1.0"
    monitoring:
      schema_drift: true
      statistical_drift: true
      data_quality: true
    drift_thresholds:
      ks_statistic: 0.1  # Warning
      ks_critical: 0.2   # Critical
      psi_warning: 0.1
      psi_critical: 0.25
      missing_rate_threshold: 0.05
    columns:
      - name: batting_average
        type: float
        drift_method: ks_test
        baseline_window: 30d
      - name: era
        type: float
        drift_method: ks_test
        baseline_window: 30d
      - name: ops_plus
        type: float
        drift_method: ks_test
      - name: leverage_index
        type: float
        drift_method: psi
      - name: readiness_score
        type: float
        drift_method: custom_cardinals

  # NFL Titans Performance
  nfl_titans:
    name: "NFL Titans Analytics"
    source: "data/nfl/titans"
    type: batch
    schema_version: "1.5.0"
    monitoring:
      schema_drift: true
      statistical_drift: true
      data_quality: true
    drift_thresholds:
      ks_statistic: 0.15
      psi_warning: 0.1
      psi_critical: 0.25
    columns:
      - name: qb_pressure_to_sack_rate
        type: float
        drift_method: ks_test
        baseline_window: 4_games
      - name: hidden_yardage_per_drive
        type: float
        drift_method: psi
        baseline_window: 5_games
      - name: defensive_efficiency
        type: float
        drift_method: ks_test

  # NBA Grizzlies Metrics
  nba_grizzlies:
    name: "NBA Grizzlies Analytics"
    source: "data/nba/grizzlies"
    type: batch
    schema_version: "1.3.0"
    monitoring:
      schema_drift: true
      statistical_drift: true
    columns:
      - name: true_shooting_pct
        type: float
        drift_method: ks_test
      - name: defensive_rating
        type: float
        drift_method: ks_test
      - name: pace_adjusted_efficiency
        type: float
        drift_method: psi

  # NCAA Longhorns Football
  ncaa_longhorns:
    name: "Texas Longhorns Football"
    source: "data/ncaa/texas-football"
    type: batch
    schema_version: "2.0.0"
    monitoring:
      schema_drift: true
      statistical_drift: true
      data_quality: true
    drift_thresholds:
      ks_statistic: 0.12
      psi_warning: 0.15
      psi_critical: 0.3
    columns:
      - name: recruiting_composite
        type: float
        drift_method: psi
      - name: sp_plus_rating
        type: float
        drift_method: ks_test
      - name: fei_ranking
        type: int
        drift_method: psi

  # Perfect Game Youth Baseball
  perfect_game:
    name: "Perfect Game Youth Baseball"
    source: "data/youth/perfect-game"
    type: batch
    schema_version: "1.8.0"
    monitoring:
      schema_drift: true
      statistical_drift: true
      data_quality: true
    drift_thresholds:
      ks_statistic: 0.1
      psi_warning: 0.2
      psi_critical: 0.4
    columns:
      - name: exit_velocity
        type: float
        drift_method: ks_test
        baseline_window: 90d
      - name: sixty_yard_dash
        type: float
        drift_method: ks_test
      - name: pg_grade
        type: float
        drift_method: psi
        bins: [0, 7.0, 8.0, 9.0, 10.0]
      - name: commitment_status
        type: categorical
        drift_method: psi

  # Texas HS Football
  texas_hs_football:
    name: "Texas High School Football (Dave Campbell's Model)"
    source: "data/texas-hs/football"
    type: batch
    schema_version: "3.1.0"
    monitoring:
      schema_drift: true
      statistical_drift: true
      data_quality: true
    drift_thresholds:
      ks_statistic: 0.15
      psi_warning: 0.1
      psi_critical: 0.3
    columns:
      - name: team_ranking
        type: int
        drift_method: psi
      - name: offensive_yards_per_game
        type: float
        drift_method: ks_test
      - name: defensive_ppg_allowed
        type: float
        drift_method: ks_test
      - name: classification
        type: categorical
        drift_method: psi
        categories: ["6A", "5A-DI", "5A-DII", "4A-DI", "4A-DII", "3A-DI", "3A-DII"]

  # Biomechanics Vision AI
  biomechanics:
    name: "Biomechanics & Character Assessment"
    source: "api/vision-ai/biomechanics"
    type: streaming
    schema_version: "1.2.0"
    monitoring:
      schema_drift: true
      statistical_drift: true
      data_quality: true
    drift_thresholds:
      ks_statistic: 0.08  # Tighter for sensor data
      psi_warning: 0.05
      psi_critical: 0.15
      latency_ms: 100  # Sub-100ms requirement
    columns:
      - name: hip_shoulder_separation_deg
        type: float
        drift_method: ks_test
        baseline_window: 7d
      - name: release_point_consistency
        type: float
        drift_method: ks_test
      - name: kinetic_chain_efficiency
        type: float
        drift_method: ks_test
      - name: micro_expression_confidence
        type: float
        drift_method: psi
      - name: character_trait_score
        type: float
        drift_method: custom_character

  # Championship Probability Models
  championship_models:
    name: "Championship Probability Engine"
    source: "models/championship-probability"
    type: batch
    schema_version: "2.5.0"
    monitoring:
      schema_drift: true
      statistical_drift: true
      model_drift: true
    drift_thresholds:
      model_accuracy_drop: 0.02
      prediction_shift: 0.1
      feature_importance_change: 0.15
    columns:
      - name: win_probability
        type: float
        drift_method: ks_test
        baseline_window: 7d
      - name: playoff_probability
        type: float
        drift_method: ks_test
      - name: championship_probability
        type: float
        drift_method: psi
        bins: [0, 0.1, 0.25, 0.5, 0.75, 1.0]

  # NIL Valuation
  nil_valuation:
    name: "NIL Valuation Calculator"
    source: "api/nil-calculator"
    type: batch
    schema_version: "1.4.0"
    monitoring:
      schema_drift: true
      statistical_drift: true
      data_quality: true
    drift_thresholds:
      ks_statistic: 0.2
      psi_warning: 0.25
      psi_critical: 0.5
    columns:
      - name: social_media_value
        type: float
        drift_method: ks_test
      - name: performance_value
        type: float
        drift_method: ks_test
      - name: market_value
        type: float
        drift_method: psi
        bins: [0, 10000, 50000, 100000, 500000, 1000000, 10000000]
      - name: total_nil_value
        type: float
        drift_method: psi

alerting:
  channels:
    - type: github
      enabled: true
      repository: "BlazeIntelligence/blazesportsintel"
      labels: ["drift-detection", "data-quality"]
      assignees: ["ahump20"]
    - type: email
      enabled: true
      recipients: ["ahump20@outlook.com"]
      smtp_host: "${SMTP_HOST}"
      smtp_port: 587
    - type: slack
      enabled: false
      webhook_url: "${SLACK_WEBHOOK_URL}"
      channel: "#data-alerts"
    - type: cloudflare_analytics
      enabled: true
      account_id: "${CLOUDFLARE_ACCOUNT_ID}"
      api_token: "${CLOUDFLARE_API_TOKEN}"

reporting:
  schedule: "0 2 * * *"  # 2 AM CT daily
  output_dir: "/observability/drift/reports"
  format: "html"
  include_visualizations: true
  sparkline_days: 30
  comparison_baseline: "30d_rolling"

  sections:
    - executive_summary
    - drift_dashboard
    - schema_changes
    - statistical_analysis
    - data_quality_metrics
    - root_cause_analysis
    - recommendations

ci_integration:
  enabled: true
  fail_on_critical: true
  cache_baselines: true
  parallel_execution: true

  gates:
    schema_changes:
      allow_new_columns: true
      allow_type_changes: false
      allow_constraint_changes: false
    statistical_drift:
      max_ks_statistic: 0.25
      max_psi: 0.5
    data_quality:
      min_completeness: 0.95
      max_duplicates: 0.01

performance:
  sampling:
    enabled: true
    strategy: "stratified"
    sample_size: 100000
    confidence_level: 0.95
  parallelization:
    enabled: true
    max_workers: 8
  caching:
    enabled: true
    ttl_seconds: 3600
    backend: "redis"

baseline_management:
  auto_update: false
  approval_required: true
  retention_days: 90
  versioning: true

  triggers:
    - type: "manual"
      description: "Manual baseline update with approval"
    - type: "scheduled"
      schedule: "0 0 1 * *"  # Monthly
      auto_approve: false
    - type: "drift_recovery"
      threshold_days: 7
      description: "Update after drift stabilizes"