/**
 * P5 College Baseball Team Registry
 *
 * Single source of truth for all 66 Power 5 conference baseball programs.
 * Slugs match the routing in app/college-baseball/teams/[teamId].
 * Colors are verified against official school brand guides.
 */

export interface CollegeBaseballTeam {
  slug: string;
  name: string;
  fullName: string;
  mascot: string;
  abbreviation: string;
  conference: 'SEC' | 'ACC' | 'Big 12' | 'Pac-12' | 'Big Ten';
  location: { city: string; state: string };
  venue: { name: string; capacity: number };
  colors: { primary: string; secondary: string };
  founded?: number;
  cwsAppearances?: number;
  nationalTitles?: number;
  rivals: string[];
}

export const CONFERENCE_META: Record<string, { fullName: string; color: string }> = {
  SEC: { fullName: 'Southeastern Conference', color: '#004B87' },
  ACC: { fullName: 'Atlantic Coast Conference', color: '#013CA6' },
  'Big 12': { fullName: 'Big 12 Conference', color: '#BF2F38' },
  'Pac-12': { fullName: 'Pac-12 Conference', color: '#004B91' },
  'Big Ten': { fullName: 'Big Ten Conference', color: '#0B1560' },
};

// ─── SEC (16) ─────────────────────────────────────────────────────────────────

const SEC: CollegeBaseballTeam[] = [
  {
    slug: 'texas',
    name: 'Texas',
    fullName: 'University of Texas at Austin',
    mascot: 'Longhorns',
    abbreviation: 'TEX',
    conference: 'SEC',
    location: { city: 'Austin', state: 'TX' },
    venue: { name: 'UFCU Disch-Falk Field', capacity: 7273 },
    colors: { primary: '#BF5700', secondary: '#FFFFFF' },
    founded: 1895,
    cwsAppearances: 38,
    nationalTitles: 6,
    rivals: ['texas-am', 'oklahoma', 'lsu'],
  },
  {
    slug: 'texas-am',
    name: 'Texas A&M',
    fullName: 'Texas A&M University',
    mascot: 'Aggies',
    abbreviation: 'TAMU',
    conference: 'SEC',
    location: { city: 'College Station', state: 'TX' },
    venue: { name: 'Blue Bell Park', capacity: 6100 },
    colors: { primary: '#500000', secondary: '#FFFFFF' },
    founded: 1893,
    cwsAppearances: 9,
    nationalTitles: 0,
    rivals: ['texas', 'lsu', 'ole-miss'],
  },
  {
    slug: 'lsu',
    name: 'LSU',
    fullName: 'Louisiana State University',
    mascot: 'Tigers',
    abbreviation: 'LSU',
    conference: 'SEC',
    location: { city: 'Baton Rouge', state: 'LA' },
    venue: { name: 'Alex Box Stadium', capacity: 10326 },
    colors: { primary: '#461D7C', secondary: '#FDD023' },
    founded: 1893,
    cwsAppearances: 19,
    nationalTitles: 7,
    rivals: ['ole-miss', 'florida', 'arkansas'],
  },
  {
    slug: 'florida',
    name: 'Florida',
    fullName: 'University of Florida',
    mascot: 'Gators',
    abbreviation: 'UF',
    conference: 'SEC',
    location: { city: 'Gainesville', state: 'FL' },
    venue: { name: 'Florida Ballpark', capacity: 7000 },
    colors: { primary: '#0021A5', secondary: '#FA4616' },
    founded: 1912,
    cwsAppearances: 13,
    nationalTitles: 2,
    rivals: ['georgia', 'miami', 'florida-state'],
  },
  {
    slug: 'arkansas',
    name: 'Arkansas',
    fullName: 'University of Arkansas',
    mascot: 'Razorbacks',
    abbreviation: 'ARK',
    conference: 'SEC',
    location: { city: 'Fayetteville', state: 'AR' },
    venue: { name: 'Baum-Walker Stadium', capacity: 11480 },
    colors: { primary: '#9D2235', secondary: '#FFFFFF' },
    founded: 1897,
    cwsAppearances: 11,
    nationalTitles: 1,
    rivals: ['lsu', 'ole-miss', 'mississippi-state'],
  },
  {
    slug: 'tennessee',
    name: 'Tennessee',
    fullName: 'University of Tennessee',
    mascot: 'Volunteers',
    abbreviation: 'TENN',
    conference: 'SEC',
    location: { city: 'Knoxville', state: 'TN' },
    venue: { name: 'Lindsey Nelson Stadium', capacity: 4340 },
    colors: { primary: '#FF8200', secondary: '#FFFFFF' },
    founded: 1893,
    cwsAppearances: 6,
    nationalTitles: 0,
    rivals: ['vanderbilt', 'florida', 'georgia'],
  },
  {
    slug: 'vanderbilt',
    name: 'Vanderbilt',
    fullName: 'Vanderbilt University',
    mascot: 'Commodores',
    abbreviation: 'VANDY',
    conference: 'SEC',
    location: { city: 'Nashville', state: 'TN' },
    venue: { name: 'Hawkins Field', capacity: 3626 },
    colors: { primary: '#866D4B', secondary: '#000000' },
    founded: 1886,
    cwsAppearances: 5,
    nationalTitles: 2,
    rivals: ['tennessee', 'florida', 'lsu'],
  },
  {
    slug: 'ole-miss',
    name: 'Ole Miss',
    fullName: 'University of Mississippi',
    mascot: 'Rebels',
    abbreviation: 'MISS',
    conference: 'SEC',
    location: { city: 'Oxford', state: 'MS' },
    venue: { name: 'Swayze Field', capacity: 10623 },
    colors: { primary: '#CE1126', secondary: '#14213D' },
    founded: 1893,
    cwsAppearances: 7,
    nationalTitles: 1,
    rivals: ['mississippi-state', 'lsu', 'arkansas'],
  },
  {
    slug: 'mississippi-state',
    name: 'Mississippi State',
    fullName: 'Mississippi State University',
    mascot: 'Bulldogs',
    abbreviation: 'MSST',
    conference: 'SEC',
    location: { city: 'Starkville', state: 'MS' },
    venue: { name: 'Dudy Noble Field', capacity: 15000 },
    colors: { primary: '#660000', secondary: '#FFFFFF' },
    founded: 1885,
    cwsAppearances: 12,
    nationalTitles: 1,
    rivals: ['ole-miss', 'lsu', 'arkansas'],
  },
  {
    slug: 'georgia',
    name: 'Georgia',
    fullName: 'University of Georgia',
    mascot: 'Bulldogs',
    abbreviation: 'UGA',
    conference: 'SEC',
    location: { city: 'Athens', state: 'GA' },
    venue: { name: 'Foley Field', capacity: 3291 },
    colors: { primary: '#BA0C2F', secondary: '#000000' },
    founded: 1886,
    cwsAppearances: 5,
    nationalTitles: 0,
    rivals: ['florida', 'georgia-tech', 'south-carolina'],
  },
  {
    slug: 'south-carolina',
    name: 'South Carolina',
    fullName: 'University of South Carolina',
    mascot: 'Gamecocks',
    abbreviation: 'SC',
    conference: 'SEC',
    location: { city: 'Columbia', state: 'SC' },
    venue: { name: 'Founders Park', capacity: 8242 },
    colors: { primary: '#73000A', secondary: '#000000' },
    founded: 1892,
    cwsAppearances: 11,
    nationalTitles: 2,
    rivals: ['clemson', 'georgia', 'florida'],
  },
  {
    slug: 'kentucky',
    name: 'Kentucky',
    fullName: 'University of Kentucky',
    mascot: 'Wildcats',
    abbreviation: 'UK',
    conference: 'SEC',
    location: { city: 'Lexington', state: 'KY' },
    venue: { name: 'Kentucky Proud Park', capacity: 3000 },
    colors: { primary: '#0033A0', secondary: '#FFFFFF' },
    founded: 1895,
    cwsAppearances: 4,
    nationalTitles: 0,
    rivals: ['vanderbilt', 'tennessee', 'louisville'],
  },
  {
    slug: 'auburn',
    name: 'Auburn',
    fullName: 'Auburn University',
    mascot: 'Tigers',
    abbreviation: 'AUB',
    conference: 'SEC',
    location: { city: 'Auburn', state: 'AL' },
    venue: { name: 'Plainsman Park', capacity: 4096 },
    colors: { primary: '#0C2340', secondary: '#E87722' },
    founded: 1895,
    cwsAppearances: 6,
    nationalTitles: 0,
    rivals: ['alabama', 'georgia', 'lsu'],
  },
  {
    slug: 'alabama',
    name: 'Alabama',
    fullName: 'University of Alabama',
    mascot: 'Crimson Tide',
    abbreviation: 'BAMA',
    conference: 'SEC',
    location: { city: 'Tuscaloosa', state: 'AL' },
    venue: { name: 'Sewell-Thomas Stadium', capacity: 6218 },
    colors: { primary: '#9E1B32', secondary: '#FFFFFF' },
    founded: 1893,
    cwsAppearances: 6,
    nationalTitles: 0,
    rivals: ['auburn', 'lsu', 'mississippi-state'],
  },
  {
    slug: 'oklahoma',
    name: 'Oklahoma',
    fullName: 'University of Oklahoma',
    mascot: 'Sooners',
    abbreviation: 'OU',
    conference: 'SEC',
    location: { city: 'Norman', state: 'OK' },
    venue: { name: 'L. Dale Mitchell Park', capacity: 3180 },
    colors: { primary: '#841617', secondary: '#FDF9D8' },
    founded: 1903,
    cwsAppearances: 10,
    nationalTitles: 2,
    rivals: ['oklahoma-state', 'texas', 'texas-am'],
  },
  {
    slug: 'missouri',
    name: 'Missouri',
    fullName: 'University of Missouri',
    mascot: 'Tigers',
    abbreviation: 'MIZ',
    conference: 'SEC',
    location: { city: 'Columbia', state: 'MO' },
    venue: { name: 'Taylor Stadium', capacity: 3031 },
    colors: { primary: '#F1B82D', secondary: '#000000' },
    founded: 1891,
    cwsAppearances: 2,
    nationalTitles: 0,
    rivals: ['arkansas', 'kentucky', 'vanderbilt'],
  },
];

// ─── ACC (14) ─────────────────────────────────────────────────────────────────

const ACC: CollegeBaseballTeam[] = [
  {
    slug: 'wake-forest',
    name: 'Wake Forest',
    fullName: 'Wake Forest University',
    mascot: 'Demon Deacons',
    abbreviation: 'WAKE',
    conference: 'ACC',
    location: { city: 'Winston-Salem', state: 'NC' },
    venue: { name: 'David F. Couch Ballpark', capacity: 3257 },
    colors: { primary: '#9E7E38', secondary: '#000000' },
    founded: 1899,
    cwsAppearances: 5,
    nationalTitles: 2,
    rivals: ['duke', 'north-carolina', 'nc-state'],
  },
  {
    slug: 'virginia',
    name: 'Virginia',
    fullName: 'University of Virginia',
    mascot: 'Cavaliers',
    abbreviation: 'UVA',
    conference: 'ACC',
    location: { city: 'Charlottesville', state: 'VA' },
    venue: { name: 'Disharoon Park', capacity: 5074 },
    colors: { primary: '#232D4B', secondary: '#F84C1E' },
    founded: 1889,
    cwsAppearances: 7,
    nationalTitles: 1,
    rivals: ['virginia-tech', 'north-carolina', 'duke'],
  },
  {
    slug: 'clemson',
    name: 'Clemson',
    fullName: 'Clemson University',
    mascot: 'Tigers',
    abbreviation: 'CLEM',
    conference: 'ACC',
    location: { city: 'Clemson', state: 'SC' },
    venue: { name: 'Doug Kingsmore Stadium', capacity: 6272 },
    colors: { primary: '#F56600', secondary: '#522D80' },
    founded: 1896,
    cwsAppearances: 13,
    nationalTitles: 0,
    rivals: ['south-carolina', 'florida-state', 'north-carolina'],
  },
  {
    slug: 'north-carolina',
    name: 'North Carolina',
    fullName: 'University of North Carolina',
    mascot: 'Tar Heels',
    abbreviation: 'UNC',
    conference: 'ACC',
    location: { city: 'Chapel Hill', state: 'NC' },
    venue: { name: 'Boshamer Stadium', capacity: 4100 },
    colors: { primary: '#7BAFD4', secondary: '#FFFFFF' },
    founded: 1889,
    cwsAppearances: 11,
    nationalTitles: 0,
    rivals: ['nc-state', 'duke', 'virginia'],
  },
  {
    slug: 'nc-state',
    name: 'NC State',
    fullName: 'North Carolina State University',
    mascot: 'Wolfpack',
    abbreviation: 'NCST',
    conference: 'ACC',
    location: { city: 'Raleigh', state: 'NC' },
    venue: { name: 'Doak Field', capacity: 3500 },
    colors: { primary: '#CC0000', secondary: '#FFFFFF' },
    founded: 1903,
    cwsAppearances: 3,
    nationalTitles: 0,
    rivals: ['north-carolina', 'duke', 'wake-forest'],
  },
  {
    slug: 'duke',
    name: 'Duke',
    fullName: 'Duke University',
    mascot: 'Blue Devils',
    abbreviation: 'DUKE',
    conference: 'ACC',
    location: { city: 'Durham', state: 'NC' },
    venue: { name: 'Jack Coombs Field', capacity: 2000 },
    colors: { primary: '#003087', secondary: '#FFFFFF' },
    founded: 1887,
    cwsAppearances: 0,
    nationalTitles: 0,
    rivals: ['north-carolina', 'nc-state', 'wake-forest'],
  },
  {
    slug: 'louisville',
    name: 'Louisville',
    fullName: 'University of Louisville',
    mascot: 'Cardinals',
    abbreviation: 'UL',
    conference: 'ACC',
    location: { city: 'Louisville', state: 'KY' },
    venue: { name: 'Jim Patterson Stadium', capacity: 4000 },
    colors: { primary: '#AD0000', secondary: '#000000' },
    founded: 1909,
    cwsAppearances: 5,
    nationalTitles: 0,
    rivals: ['kentucky', 'virginia', 'clemson'],
  },
  {
    slug: 'miami',
    name: 'Miami',
    fullName: 'University of Miami',
    mascot: 'Hurricanes',
    abbreviation: 'MIA',
    conference: 'ACC',
    location: { city: 'Coral Gables', state: 'FL' },
    venue: { name: 'Mark Light Field', capacity: 5000 },
    colors: { primary: '#F47321', secondary: '#005030' },
    founded: 1940,
    cwsAppearances: 25,
    nationalTitles: 4,
    rivals: ['florida', 'florida-state', 'clemson'],
  },
  {
    slug: 'florida-state',
    name: 'Florida State',
    fullName: 'Florida State University',
    mascot: 'Seminoles',
    abbreviation: 'FSU',
    conference: 'ACC',
    location: { city: 'Tallahassee', state: 'FL' },
    venue: { name: 'Dick Howser Stadium', capacity: 6700 },
    colors: { primary: '#782F40', secondary: '#CEB888' },
    founded: 1948,
    cwsAppearances: 23,
    nationalTitles: 1,
    rivals: ['florida', 'miami', 'clemson'],
  },
  {
    slug: 'virginia-tech',
    name: 'Virginia Tech',
    fullName: 'Virginia Polytechnic Institute',
    mascot: 'Hokies',
    abbreviation: 'VT',
    conference: 'ACC',
    location: { city: 'Blacksburg', state: 'VA' },
    venue: { name: 'English Field', capacity: 3000 },
    colors: { primary: '#630031', secondary: '#CF4420' },
    founded: 1897,
    cwsAppearances: 0,
    nationalTitles: 0,
    rivals: ['virginia', 'duke', 'north-carolina'],
  },
  {
    slug: 'georgia-tech',
    name: 'Georgia Tech',
    fullName: 'Georgia Institute of Technology',
    mascot: 'Yellow Jackets',
    abbreviation: 'GT',
    conference: 'ACC',
    location: { city: 'Atlanta', state: 'GA' },
    venue: { name: 'Russ Chandler Stadium', capacity: 4157 },
    colors: { primary: '#B3A369', secondary: '#003057' },
    founded: 1892,
    cwsAppearances: 5,
    nationalTitles: 0,
    rivals: ['georgia', 'clemson', 'florida-state'],
  },
  {
    slug: 'notre-dame',
    name: 'Notre Dame',
    fullName: 'University of Notre Dame',
    mascot: 'Fighting Irish',
    abbreviation: 'ND',
    conference: 'ACC',
    location: { city: 'Notre Dame', state: 'IN' },
    venue: { name: 'Frank Eck Stadium', capacity: 2500 },
    colors: { primary: '#0C2340', secondary: '#C99700' },
    founded: 1892,
    cwsAppearances: 3,
    nationalTitles: 0,
    rivals: ['pittsburgh', 'louisville', 'virginia'],
  },
  {
    slug: 'pittsburgh',
    name: 'Pittsburgh',
    fullName: 'University of Pittsburgh',
    mascot: 'Panthers',
    abbreviation: 'PITT',
    conference: 'ACC',
    location: { city: 'Pittsburgh', state: 'PA' },
    venue: { name: 'Charles L. Cost Field', capacity: 2800 },
    colors: { primary: '#003594', secondary: '#FFB81C' },
    founded: 1869,
    cwsAppearances: 1,
    nationalTitles: 0,
    rivals: ['notre-dame', 'virginia-tech', 'boston-college'],
  },
  {
    slug: 'boston-college',
    name: 'Boston College',
    fullName: 'Boston College',
    mascot: 'Eagles',
    abbreviation: 'BC',
    conference: 'ACC',
    location: { city: 'Chestnut Hill', state: 'MA' },
    venue: { name: 'Eddie Pellagrini Diamond', capacity: 1000 },
    colors: { primary: '#98002E', secondary: '#BC9B6A' },
    founded: 1919,
    cwsAppearances: 0,
    nationalTitles: 0,
    rivals: ['notre-dame', 'pittsburgh', 'virginia-tech'],
  },
];

// ─── Big 12 (15) ──────────────────────────────────────────────────────────────

const BIG12: CollegeBaseballTeam[] = [
  {
    slug: 'tcu',
    name: 'TCU',
    fullName: 'Texas Christian University',
    mascot: 'Horned Frogs',
    abbreviation: 'TCU',
    conference: 'Big 12',
    location: { city: 'Fort Worth', state: 'TX' },
    venue: { name: 'Lupton Stadium', capacity: 4500 },
    colors: { primary: '#4D1979', secondary: '#FFFFFF' },
    founded: 1896,
    cwsAppearances: 6,
    nationalTitles: 0,
    rivals: ['texas-tech', 'baylor', 'oklahoma-state'],
  },
  {
    slug: 'texas-tech',
    name: 'Texas Tech',
    fullName: 'Texas Tech University',
    mascot: 'Red Raiders',
    abbreviation: 'TTU',
    conference: 'Big 12',
    location: { city: 'Lubbock', state: 'TX' },
    venue: { name: 'Dan Law Field', capacity: 4432 },
    colors: { primary: '#CC0000', secondary: '#000000' },
    founded: 1926,
    cwsAppearances: 5,
    nationalTitles: 0,
    rivals: ['tcu', 'baylor', 'oklahoma-state'],
  },
  {
    slug: 'oklahoma-state',
    name: 'Oklahoma State',
    fullName: 'Oklahoma State University',
    mascot: 'Cowboys',
    abbreviation: 'OKST',
    conference: 'Big 12',
    location: { city: 'Stillwater', state: 'OK' },
    venue: { name: "O'Brate Stadium", capacity: 4000 },
    colors: { primary: '#FF7300', secondary: '#000000' },
    founded: 1904,
    cwsAppearances: 20,
    nationalTitles: 1,
    rivals: ['oklahoma', 'tcu', 'texas-tech'],
  },
  {
    slug: 'kansas-state',
    name: 'Kansas State',
    fullName: 'Kansas State University',
    mascot: 'Wildcats',
    abbreviation: 'KSU',
    conference: 'Big 12',
    location: { city: 'Manhattan', state: 'KS' },
    venue: { name: 'Tointon Family Stadium', capacity: 2331 },
    colors: { primary: '#512888', secondary: '#FFFFFF' },
    founded: 1886,
    cwsAppearances: 1,
    nationalTitles: 0,
    rivals: ['baylor', 'tcu', 'west-virginia'],
  },
  {
    slug: 'west-virginia',
    name: 'West Virginia',
    fullName: 'West Virginia University',
    mascot: 'Mountaineers',
    abbreviation: 'WVU',
    conference: 'Big 12',
    location: { city: 'Morgantown', state: 'WV' },
    venue: { name: 'Monongalia County Ballpark', capacity: 3500 },
    colors: { primary: '#002855', secondary: '#EAAA00' },
    founded: 1892,
    cwsAppearances: 0,
    nationalTitles: 0,
    rivals: ['pittsburgh', 'kansas-state', 'cincinnati'],
  },
  {
    slug: 'baylor',
    name: 'Baylor',
    fullName: 'Baylor University',
    mascot: 'Bears',
    abbreviation: 'BAY',
    conference: 'Big 12',
    location: { city: 'Waco', state: 'TX' },
    venue: { name: 'Baylor Ballpark', capacity: 5000 },
    colors: { primary: '#154734', secondary: '#FFB81C' },
    founded: 1899,
    cwsAppearances: 3,
    nationalTitles: 0,
    rivals: ['tcu', 'texas-tech', 'houston'],
  },
  {
    slug: 'kansas',
    name: 'Kansas',
    fullName: 'University of Kansas',
    mascot: 'Jayhawks',
    abbreviation: 'KU',
    conference: 'Big 12',
    location: { city: 'Lawrence', state: 'KS' },
    venue: { name: 'Hoglund Ballpark', capacity: 2500 },
    colors: { primary: '#0051BA', secondary: '#E8000D' },
    founded: 1870,
    cwsAppearances: 2,
    nationalTitles: 0,
    rivals: ['kansas-state', 'baylor', 'oklahoma-state'],
  },
  {
    slug: 'byu',
    name: 'BYU',
    fullName: 'Brigham Young University',
    mascot: 'Cougars',
    abbreviation: 'BYU',
    conference: 'Big 12',
    location: { city: 'Provo', state: 'UT' },
    venue: { name: 'Larry H. Miller Field', capacity: 2500 },
    colors: { primary: '#002E5D', secondary: '#FFFFFF' },
    founded: 1913,
    cwsAppearances: 0,
    nationalTitles: 0,
    rivals: ['utah', 'arizona-state', 'ucf'],
  },
  {
    slug: 'ucf',
    name: 'UCF',
    fullName: 'University of Central Florida',
    mascot: 'Knights',
    abbreviation: 'UCF',
    conference: 'Big 12',
    location: { city: 'Orlando', state: 'FL' },
    venue: { name: 'John Euliano Park', capacity: 3584 },
    colors: { primary: '#000000', secondary: '#FFC904' },
    founded: 1973,
    cwsAppearances: 1,
    nationalTitles: 0,
    rivals: ['houston', 'cincinnati', 'byu'],
  },
  {
    slug: 'houston',
    name: 'Houston',
    fullName: 'University of Houston',
    mascot: 'Cougars',
    abbreviation: 'UH',
    conference: 'Big 12',
    location: { city: 'Houston', state: 'TX' },
    venue: { name: 'Darryl & Lori Schroeder Park', capacity: 5000 },
    colors: { primary: '#C8102E', secondary: '#FFFFFF' },
    founded: 1928,
    cwsAppearances: 6,
    nationalTitles: 0,
    rivals: ['baylor', 'ucf', 'cincinnati'],
  },
  {
    slug: 'cincinnati',
    name: 'Cincinnati',
    fullName: 'University of Cincinnati',
    mascot: 'Bearcats',
    abbreviation: 'CIN',
    conference: 'Big 12',
    location: { city: 'Cincinnati', state: 'OH' },
    venue: { name: 'UC Baseball Stadium', capacity: 3085 },
    colors: { primary: '#E00122', secondary: '#000000' },
    founded: 1901,
    cwsAppearances: 0,
    nationalTitles: 0,
    rivals: ['west-virginia', 'houston', 'ucf'],
  },
  {
    slug: 'arizona',
    name: 'Arizona',
    fullName: 'University of Arizona',
    mascot: 'Wildcats',
    abbreviation: 'ZONA',
    conference: 'Big 12',
    location: { city: 'Tucson', state: 'AZ' },
    venue: { name: 'Hi Corbett Field', capacity: 9500 },
    colors: { primary: '#CC0033', secondary: '#003366' },
    founded: 1906,
    cwsAppearances: 18,
    nationalTitles: 4,
    rivals: ['arizona-state', 'ucla', 'usc'],
  },
  {
    slug: 'arizona-state',
    name: 'Arizona State',
    fullName: 'Arizona State University',
    mascot: 'Sun Devils',
    abbreviation: 'ASU',
    conference: 'Big 12',
    location: { city: 'Tempe', state: 'AZ' },
    venue: { name: 'Phoenix Municipal Stadium', capacity: 8775 },
    colors: { primary: '#8C1D40', secondary: '#FFC627' },
    founded: 1907,
    cwsAppearances: 22,
    nationalTitles: 5,
    rivals: ['arizona', 'usc', 'stanford'],
  },
  {
    slug: 'colorado',
    name: 'Colorado',
    fullName: 'University of Colorado',
    mascot: 'Buffaloes',
    abbreviation: 'CU',
    conference: 'Big 12',
    location: { city: 'Boulder', state: 'CO' },
    venue: { name: 'CU Baseball Field', capacity: 1500 },
    colors: { primary: '#CFB87C', secondary: '#000000' },
    founded: 2024,
    cwsAppearances: 0,
    nationalTitles: 0,
    rivals: ['utah', 'byu', 'arizona-state'],
  },
  {
    slug: 'utah',
    name: 'Utah',
    fullName: 'University of Utah',
    mascot: 'Utes',
    abbreviation: 'UTAH',
    conference: 'Big 12',
    location: { city: 'Salt Lake City', state: 'UT' },
    venue: { name: 'Smith Ballpark', capacity: 14000 },
    colors: { primary: '#CC0000', secondary: '#FFFFFF' },
    founded: 2025,
    cwsAppearances: 0,
    nationalTitles: 0,
    rivals: ['byu', 'colorado', 'arizona'],
  },
];

// ─── Pac-12 (8) ───────────────────────────────────────────────────────────────

const PAC12: CollegeBaseballTeam[] = [
  {
    slug: 'oregon-state',
    name: 'Oregon State',
    fullName: 'Oregon State University',
    mascot: 'Beavers',
    abbreviation: 'ORST',
    conference: 'Pac-12',
    location: { city: 'Corvallis', state: 'OR' },
    venue: { name: 'Goss Stadium', capacity: 4016 },
    colors: { primary: '#DC4405', secondary: '#000000' },
    founded: 1907,
    cwsAppearances: 7,
    nationalTitles: 3,
    rivals: ['oregon', 'stanford', 'washington-state'],
  },
  {
    slug: 'stanford',
    name: 'Stanford',
    fullName: 'Stanford University',
    mascot: 'Cardinal',
    abbreviation: 'STAN',
    conference: 'Pac-12',
    location: { city: 'Stanford', state: 'CA' },
    venue: { name: 'Sunken Diamond', capacity: 4000 },
    colors: { primary: '#8C1515', secondary: '#FFFFFF' },
    founded: 1892,
    cwsAppearances: 22,
    nationalTitles: 2,
    rivals: ['california', 'oregon-state', 'ucla'],
  },
  {
    slug: 'ucla',
    name: 'UCLA',
    fullName: 'University of California, Los Angeles',
    mascot: 'Bruins',
    abbreviation: 'UCLA',
    conference: 'Pac-12',
    location: { city: 'Los Angeles', state: 'CA' },
    venue: { name: 'Jackie Robinson Stadium', capacity: 1820 },
    colors: { primary: '#2D68C4', secondary: '#F2A900' },
    founded: 1920,
    cwsAppearances: 6,
    nationalTitles: 1,
    rivals: ['usc', 'stanford', 'california'],
  },
  {
    slug: 'usc',
    name: 'USC',
    fullName: 'University of Southern California',
    mascot: 'Trojans',
    abbreviation: 'USC',
    conference: 'Pac-12',
    location: { city: 'Los Angeles', state: 'CA' },
    venue: { name: 'Dedeaux Field', capacity: 2500 },
    colors: { primary: '#990000', secondary: '#FFC72C' },
    founded: 1888,
    cwsAppearances: 22,
    nationalTitles: 12,
    rivals: ['ucla', 'stanford', 'arizona-state'],
  },
  {
    slug: 'california',
    name: 'Cal',
    fullName: 'University of California, Berkeley',
    mascot: 'Golden Bears',
    abbreviation: 'CAL',
    conference: 'Pac-12',
    location: { city: 'Berkeley', state: 'CA' },
    venue: { name: 'Evans Diamond', capacity: 2500 },
    colors: { primary: '#003262', secondary: '#FDB515' },
    founded: 1892,
    cwsAppearances: 2,
    nationalTitles: 1,
    rivals: ['stanford', 'ucla', 'oregon-state'],
  },
  {
    slug: 'washington',
    name: 'Washington',
    fullName: 'University of Washington',
    mascot: 'Huskies',
    abbreviation: 'UW',
    conference: 'Pac-12',
    location: { city: 'Seattle', state: 'WA' },
    venue: { name: 'Husky Ballpark', capacity: 2200 },
    colors: { primary: '#4B2E83', secondary: '#E8D3A2' },
    founded: 1902,
    cwsAppearances: 3,
    nationalTitles: 0,
    rivals: ['washington-state', 'oregon', 'oregon-state'],
  },
  {
    slug: 'oregon',
    name: 'Oregon',
    fullName: 'University of Oregon',
    mascot: 'Ducks',
    abbreviation: 'ORE',
    conference: 'Pac-12',
    location: { city: 'Eugene', state: 'OR' },
    venue: { name: 'PK Park', capacity: 4000 },
    colors: { primary: '#154733', secondary: '#FEE123' },
    founded: 1876,
    cwsAppearances: 3,
    nationalTitles: 0,
    rivals: ['oregon-state', 'washington', 'stanford'],
  },
  {
    slug: 'washington-state',
    name: 'Washington State',
    fullName: 'Washington State University',
    mascot: 'Cougars',
    abbreviation: 'WSU',
    conference: 'Pac-12',
    location: { city: 'Pullman', state: 'WA' },
    venue: { name: 'Bailey-Brayton Field', capacity: 3500 },
    colors: { primary: '#981E32', secondary: '#5E6A71' },
    founded: 1892,
    cwsAppearances: 2,
    nationalTitles: 0,
    rivals: ['washington', 'oregon-state', 'oregon'],
  },
];

// ─── Big Ten (13) ─────────────────────────────────────────────────────────────

const BIGTEN: CollegeBaseballTeam[] = [
  {
    slug: 'indiana',
    name: 'Indiana',
    fullName: 'Indiana University',
    mascot: 'Hoosiers',
    abbreviation: 'IU',
    conference: 'Big Ten',
    location: { city: 'Bloomington', state: 'IN' },
    venue: { name: 'Bart Kaufman Field', capacity: 3000 },
    colors: { primary: '#990000', secondary: '#FFFFFF' },
    founded: 1893,
    cwsAppearances: 3,
    nationalTitles: 0,
    rivals: ['purdue', 'ohio-state', 'michigan'],
  },
  {
    slug: 'maryland',
    name: 'Maryland',
    fullName: 'University of Maryland',
    mascot: 'Terrapins',
    abbreviation: 'UMD',
    conference: 'Big Ten',
    location: { city: 'College Park', state: 'MD' },
    venue: { name: 'Bob "Turtle" Smith Stadium', capacity: 2500 },
    colors: { primary: '#E03A3E', secondary: '#FFD520' },
    founded: 1893,
    cwsAppearances: 0,
    nationalTitles: 0,
    rivals: ['rutgers', 'penn-state', 'michigan'],
  },
  {
    slug: 'michigan',
    name: 'Michigan',
    fullName: 'University of Michigan',
    mascot: 'Wolverines',
    abbreviation: 'MICH',
    conference: 'Big Ten',
    location: { city: 'Ann Arbor', state: 'MI' },
    venue: { name: 'Ray Fisher Stadium', capacity: 4000 },
    colors: { primary: '#00274C', secondary: '#FFCB05' },
    founded: 1866,
    cwsAppearances: 8,
    nationalTitles: 2,
    rivals: ['michigan-state', 'ohio-state', 'indiana'],
  },
  {
    slug: 'ohio-state',
    name: 'Ohio State',
    fullName: 'Ohio State University',
    mascot: 'Buckeyes',
    abbreviation: 'OSU',
    conference: 'Big Ten',
    location: { city: 'Columbus', state: 'OH' },
    venue: { name: 'Bill Davis Stadium', capacity: 4450 },
    colors: { primary: '#BB0000', secondary: '#666666' },
    founded: 1881,
    cwsAppearances: 4,
    nationalTitles: 0,
    rivals: ['michigan', 'indiana', 'penn-state'],
  },
  {
    slug: 'penn-state',
    name: 'Penn State',
    fullName: 'Pennsylvania State University',
    mascot: 'Nittany Lions',
    abbreviation: 'PSU',
    conference: 'Big Ten',
    location: { city: 'University Park', state: 'PA' },
    venue: { name: 'Medlar Field', capacity: 5406 },
    colors: { primary: '#041E42', secondary: '#FFFFFF' },
    founded: 1875,
    cwsAppearances: 0,
    nationalTitles: 0,
    rivals: ['ohio-state', 'maryland', 'rutgers'],
  },
  {
    slug: 'rutgers',
    name: 'Rutgers',
    fullName: 'Rutgers University',
    mascot: 'Scarlet Knights',
    abbreviation: 'RU',
    conference: 'Big Ten',
    location: { city: 'Piscataway', state: 'NJ' },
    venue: { name: 'Bainton Field', capacity: 1500 },
    colors: { primary: '#CC0033', secondary: '#5F6A72' },
    founded: 1866,
    cwsAppearances: 0,
    nationalTitles: 0,
    rivals: ['penn-state', 'maryland', 'michigan'],
  },
  {
    slug: 'nebraska',
    name: 'Nebraska',
    fullName: 'University of Nebraska',
    mascot: 'Cornhuskers',
    abbreviation: 'NEB',
    conference: 'Big Ten',
    location: { city: 'Lincoln', state: 'NE' },
    venue: { name: 'Hawks Field', capacity: 8486 },
    colors: { primary: '#E41C38', secondary: '#F5F1E7' },
    founded: 1890,
    cwsAppearances: 3,
    nationalTitles: 0,
    rivals: ['minnesota', 'iowa', 'michigan'],
  },
  {
    slug: 'minnesota',
    name: 'Minnesota',
    fullName: 'University of Minnesota',
    mascot: 'Golden Gophers',
    abbreviation: 'MINN',
    conference: 'Big Ten',
    location: { city: 'Minneapolis', state: 'MN' },
    venue: { name: 'Siebert Field', capacity: 1500 },
    colors: { primary: '#7A0019', secondary: '#FFCC33' },
    founded: 1876,
    cwsAppearances: 6,
    nationalTitles: 3,
    rivals: ['iowa', 'nebraska', 'illinois'],
  },
  {
    slug: 'iowa',
    name: 'Iowa',
    fullName: 'University of Iowa',
    mascot: 'Hawkeyes',
    abbreviation: 'IOWA',
    conference: 'Big Ten',
    location: { city: 'Iowa City', state: 'IA' },
    venue: { name: 'Duane Banks Field', capacity: 3000 },
    colors: { primary: '#FFCD00', secondary: '#000000' },
    founded: 1882,
    cwsAppearances: 1,
    nationalTitles: 0,
    rivals: ['minnesota', 'nebraska', 'illinois'],
  },
  {
    slug: 'illinois',
    name: 'Illinois',
    fullName: 'University of Illinois',
    mascot: 'Fighting Illini',
    abbreviation: 'ILL',
    conference: 'Big Ten',
    location: { city: 'Champaign', state: 'IL' },
    venue: { name: 'Illinois Field', capacity: 3000 },
    colors: { primary: '#E84A27', secondary: '#13294B' },
    founded: 1879,
    cwsAppearances: 2,
    nationalTitles: 0,
    rivals: ['purdue', 'northwestern', 'iowa'],
  },
  {
    slug: 'northwestern',
    name: 'Northwestern',
    fullName: 'Northwestern University',
    mascot: 'Wildcats',
    abbreviation: 'NW',
    conference: 'Big Ten',
    location: { city: 'Evanston', state: 'IL' },
    venue: { name: 'Rocky Miller Park', capacity: 1200 },
    colors: { primary: '#4E2A84', secondary: '#FFFFFF' },
    founded: 1880,
    cwsAppearances: 0,
    nationalTitles: 0,
    rivals: ['illinois', 'purdue', 'michigan'],
  },
  {
    slug: 'purdue',
    name: 'Purdue',
    fullName: 'Purdue University',
    mascot: 'Boilermakers',
    abbreviation: 'PUR',
    conference: 'Big Ten',
    location: { city: 'West Lafayette', state: 'IN' },
    venue: { name: 'Alexander Field', capacity: 2000 },
    colors: { primary: '#CEB888', secondary: '#000000' },
    founded: 1891,
    cwsAppearances: 0,
    nationalTitles: 0,
    rivals: ['indiana', 'illinois', 'northwestern'],
  },
  {
    slug: 'michigan-state',
    name: 'Michigan State',
    fullName: 'Michigan State University',
    mascot: 'Spartans',
    abbreviation: 'MSU',
    conference: 'Big Ten',
    location: { city: 'East Lansing', state: 'MI' },
    venue: { name: 'McLane Baseball Stadium', capacity: 2500 },
    colors: { primary: '#18453B', secondary: '#FFFFFF' },
    founded: 1884,
    cwsAppearances: 3,
    nationalTitles: 0,
    rivals: ['michigan', 'ohio-state', 'indiana'],
  },
];

// ─── Combined Registry ────────────────────────────────────────────────────────

export const COLLEGE_BASEBALL_TEAMS: CollegeBaseballTeam[] = [
  ...SEC,
  ...ACC,
  ...BIG12,
  ...PAC12,
  ...BIGTEN,
];

const slugIndex = new Map(COLLEGE_BASEBALL_TEAMS.map((t) => [t.slug, t]));

export function getTeamBySlug(slug: string): CollegeBaseballTeam | undefined {
  return slugIndex.get(slug);
}

export function getTeamsByConference(conference: string): CollegeBaseballTeam[] {
  return COLLEGE_BASEBALL_TEAMS.filter((t) => t.conference === conference);
}
