# Championship Intelligence Platform - Cloudflare Workers Configuration
# Production-grade deployment with API Gateway integration

name = "blaze-championship-intelligence"
compatibility_date = "2025-01-26"
compatibility_flags = [ "nodejs_compat" ]

# Main site routing
[site]
bucket = "./dist"

# Environment Variables
[env.production.vars]
ENVIRONMENT = "production"
MCP_SERVER_URL = "http://localhost:3001"
MCP_TOKEN = "blaze-intelligence-championship-token"
API_BASE_URL = "https://blazesportsintel.com/api"

# KV Namespaces for caching
[[kv_namespaces]]
binding = "SPORTS_CACHE"
id = "sports_data_cache"
preview_id = "sports_data_cache_preview"

[[kv_namespaces]]
binding = "MCP_CACHE"
id = "mcp_data_cache"
preview_id = "mcp_data_cache_preview"

# R2 Storage for assets
[[r2_buckets]]
binding = "MEDIA_STORAGE"
bucket_name = "blaze-intelligence-media"

[[r2_buckets]]
binding = "DATA_STORAGE"
bucket_name = "blaze-intelligence-data"

# D1 Database for analytics
[[d1_databases]]
binding = "ANALYTICS_DB"
database_name = "blaze-analytics"
database_id = "championship-analytics-db"

# Workers routes for API endpoints
[[routes]]
pattern = "blazesportsintel.com/api/*"
custom_domain = true

[[routes]]
pattern = "*.blazesportsintel.pages.dev/api/*"
custom_domain = false

# Build configuration
[build]
command = "echo 'No build required - static site with inline JavaScript'"
cwd = "."
watch_dir = "."

# Site configuration
[site]
bucket = "."
include = ["*.html", "*.js", "*.css", "*.json", "*.png", "*.jpg", "*.svg", "api/**/*"]
exclude = ["node_modules", "*.md", "*.log", ".*"]

# Custom headers
[[rules]]
path = "*.js"
headers = { "Content-Type" = "application/javascript; charset=utf-8", "Cache-Control" = "public, max-age=3600" }

[[rules]]
path = "*.css"
headers = { "Content-Type" = "text/css; charset=utf-8", "Cache-Control" = "public, max-age=3600" }

[[rules]]
path = "*.json"
headers = { "Content-Type" = "application/json; charset=utf-8", "Cache-Control" = "public, max-age=300" }

[[rules]]
path = "*.html"
headers = { "Content-Type" = "text/html; charset=utf-8", "Cache-Control" = "public, max-age=300", "X-Frame-Options" = "SAMEORIGIN", "X-Content-Type-Options" = "nosniff", "Referrer-Policy" = "strict-origin-when-cross-origin" }

[[rules]]
path = "/api/*"
headers = { "Content-Type" = "application/json; charset=utf-8", "Access-Control-Allow-Origin" = "*", "Access-Control-Allow-Methods" = "GET, POST, OPTIONS", "Access-Control-Allow-Headers" = "Content-Type, Authorization" }

# Analytics and monitoring
[observability]
enabled = true

# Workers configuration for API gateway
[workers]
main = "./api/championship-intelligence-gateway.js"
compatibility_date = "2025-01-26"
compatibility_flags = [ "nodejs_compat" ]

# Rate limiting
[limits]
cpu_ms = 50000