# BLAZE SPORTS INTEL - CLOUDFLARE PAGES CONFIGURATION
# Deep South Sports Authority Platform - blazesportsintel.com
# Transform Data Into Championships

name = "blazesportsintel"

# Pages Build Configuration
[build]
command = ""
cwd = "."
watch_dir = "."

# Production Environment
[env.production]
vars = {
  ENVIRONMENT = "production",
  API_VERSION = "v1",
  SPORTS_DATA_REFRESH_INTERVAL = "300",
  CACHE_TTL = "3600"
}

# Preview Environment
[env.preview]
vars = {
  ENVIRONMENT = "preview",
  API_VERSION = "v1-preview",
  SPORTS_DATA_REFRESH_INTERVAL = "60",
  CACHE_TTL = "300"
}