/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 74a76b7ecd8c8aa01bd7e2735d3c5721)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		RATE_LIMIT_KV: KVNamespace;
		TEAM_STATS_KV: KVNamespace;
		BSI_WORKER: Fetcher /* blazesportsintel-worker-prod */;
	}
}
interface Env extends Cloudflare.Env {}
