global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'bsi-monitor'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Python API service
  - job_name: 'bsi-api'
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'api'
          component: 'backend'
    metrics_path: '/metrics'

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'redis'
          component: 'cache'

  # PostgreSQL (via postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
        labels:
          service: 'postgres'
          component: 'database'

  # MinIO
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
        labels:
          service: 'minio'
          component: 'storage'
    metrics_path: '/minio/v2/metrics/cluster'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          service: 'node-exporter'
          component: 'system'

  # Cloudflare Workers (if accessible)
  - job_name: 'cloudflare'
    static_configs:
      - targets: ['wrangler:8787']
        labels:
          service: 'cloudflare'
          component: 'edge'

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
        labels:
          service: 'docker'
          component: 'container'