/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime --config workers/bsi-portal-sync/wrangler.toml workers/bsi-portal-sync/env.d.ts` (hash: 918ffb33f4df6158278c3250e95ac9e3)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		KV: KVNamespace;
	}
}
interface Env extends Cloudflare.Env {}
