/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime --config workers/blaze-field-site/wrangler.toml workers/blaze-field-site/env.d.ts` (hash: a8617ed93a30e2deb46fd8eb7ed1465d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface ProductionEnv {
		MONITOR_KV: KVNamespace;
		ASSETS: R2Bucket;
	}
	interface Env {
		MONITOR_KV: KVNamespace;
		ASSETS: R2Bucket;
	}
}
interface Env extends Cloudflare.Env {}
