/**
 * Blaze Field — BlazeCraft CDN + API Worker
 *
 * Serves the Canvas2D game dashboard from R2 and provides:
 * - /api/status — synthetic monitor results from MONITOR_KV
 * - /api/agent-events — recent Claude Code hook events for wisp rendering
 * - /api/events/ingest — POST endpoint for hook event ingestion
 * - Cache-Control: immutable for hashed assets, 5min for index.html
 * - COOP/COEP security headers, custom 404
 */

// Env generated by wrangler types → env.d.ts

const SECURITY_HEADERS = {
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Embedder-Policy': 'require-corp',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
};

const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.wasm': 'application/wasm',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.glb': 'model/gltf-binary',
  '.gltf': 'application/gltf+json',
  '.webmanifest': 'application/manifest+json',
  '.webp': 'image/webp',
  '.mp3': 'audio/mpeg',
  '.ogg': 'audio/ogg',
  '.wav': 'audio/wav',
};

/** Origins allowed to POST to this worker. */
const ALLOWED_POST_ORIGINS = [
  'https://blazecraft.app',
  'http://localhost:5173',
  'http://localhost:8791',
];

/** Returns the origin header if it's in the allow list, or empty string if not. */
function corsOrigin(request: Request): string {
  const origin = request.headers.get('Origin') ?? '';
  return ALLOWED_POST_ORIGINS.includes(origin) ? origin : '';
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    // Analytics beacon — restrict to known origins
    if (url.pathname === '/api/beacon' && request.method === 'POST') {
      const origin = corsOrigin(request);
      return new Response(null, {
        status: 204,
        headers: origin ? { 'Access-Control-Allow-Origin': origin } : {},
      });
    }

    // CORS preflight for API routes
    if (request.method === 'OPTIONS' && url.pathname.startsWith('/api/')) {
      const isPostRoute = url.pathname === '/api/events/ingest'
        || url.pathname === '/api/blazecraft/events'
        || url.pathname === '/api/beacon';

      const origin = isPostRoute ? corsOrigin(request) : '*';
      if (isPostRoute && !origin) {
        return new Response(null, { status: 204, headers: {} });
      }
      return new Response(null, {
        status: 204,
        headers: {
          'Access-Control-Allow-Origin': origin,
          'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
          'Access-Control-Allow-Headers': 'Content-Type, Authorization',
          'Access-Control-Max-Age': '86400',
        },
      });
    }

    // Agent event ingestion — receives tool use events from Claude Code hooks
    if ((url.pathname === '/api/blazecraft/events' || url.pathname === '/api/events/ingest') && request.method === 'POST') {
      return handleEventIngest(request, env);
    }

    // Agent events — returns recent events for dashboard
    if (url.pathname === '/api/agent-events') {
      return handleAgentEvents(env);
    }

    // Bug tracker — aggregates monitor failures + recent errors for game overlay
    if (url.pathname === '/api/bugs') {
      return handleBugs(env);
    }

    // Infrastructure status — reads synthetic monitor results from KV
    if (url.pathname === '/api/status') {
      const latest = await env.MONITOR_KV.get('summary:latest', 'text');
      if (!latest) {
        return new Response(JSON.stringify({ error: 'No monitoring data yet' }), {
          status: 404,
          headers: {
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin': '*',
            'Cache-Control': 'no-cache',
          },
        });
      }
      const parsed = JSON.parse(latest) as Record<string, unknown>;
      const bugReport = await collectBugReport(env);
      const blockingIssues = bugReport.bugs.filter(
        (bug) => bug.severity === 'high' || bug.severity === 'critical',
      ).length;
      const statusPayload = {
        ...parsed,
        allHealthy: Boolean(parsed.allHealthy) && blockingIssues === 0,
        issueSummary: {
          activeBugs: bugReport.summary.active,
          highSeverityBugs: blockingIssues,
          updatedAt: bugReport.timestamp,
        },
      };
      return new Response(JSON.stringify(statusPayload), {
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
          'Cache-Control': 'public, max-age=30',
        },
      });
    }

    // Determine asset path
    let path = url.pathname === '/' ? 'index.html' : url.pathname.slice(1);

    // Try R2
    const object = await env.ASSETS.get(path);
    if (!object) {
      // SPA fallback — serve index.html for non-asset paths
      const ext = path.includes('.') ? path.slice(path.lastIndexOf('.')) : '';
      if (!ext) {
        const fallback = await env.ASSETS.get('index.html');
        if (fallback) {
          return buildResponse(fallback, 'index.html', false);
        }
      }
      return new Response(notFoundHtml(), {
        status: 404,
        headers: { 'Content-Type': 'text/html; charset=utf-8', ...SECURITY_HEADERS },
      });
    }

    const isHashed = /[-\.][a-zA-Z0-9]{8,}\.(js|css|wasm|glb|png|jpg|webp)$/.test(path);
    return buildResponse(object, path, isHashed);
  },
} satisfies ExportedHandler<Env>;

const SESSION_KEY_PREFIX = 'agent:session:';
const SESSION_INDEX_KEY = 'agent:sessions';
const MAX_EVENTS_PER_SESSION = 20;
const MAX_SESSIONS = 20;
const EVENT_TTL = 3600; // 1 hour

interface AgentEvent {
  type: string;
  agentId: string;
  agentName: string;
  sessionId?: string;
  timestamp: string;
  data?: Record<string, unknown>;
  receivedAt: string;
}

interface SessionEntry {
  id: string;
  lastSeen: string;
}

interface PublicAgentAlias {
  agentId: string;
  agentName: string;
}

function createPublicAgentAlias(index: number): PublicAgentAlias {
  const suffix = String(index).padStart(2, '0');
  return {
    agentId: `field-unit-${suffix}`,
    agentName: `Field Unit ${suffix}`,
  };
}

function describePublicEvent(type: string): string {
  const normalized = type.replace(/[_-]+/g, ' ').trim();
  return normalized.length > 0 ? normalized : 'activity';
}

function sanitizeEventData(data: Record<string, unknown> | undefined, fallbackType: string) {
  const fallbackMessage = describePublicEvent(fallbackType);
  if (!data) {
    return {
      message: fallbackMessage,
    };
  }

  const buildingKind =
    typeof data.buildingKind === 'string' ? data.buildingKind.slice(0, 40) : undefined;

  return {
    ...(buildingKind ? { buildingKind } : {}),
    message: buildingKind ? `${buildingKind} action` : fallbackMessage,
  };
}

function sanitizeAgentEvent(event: AgentEvent, alias: PublicAgentAlias): AgentEvent {
  return {
    type: event.type,
    agentId: alias.agentId,
    agentName: alias.agentName,
    timestamp: event.timestamp,
    data: sanitizeEventData(event.data, event.type),
    receivedAt: event.receivedAt,
  };
}

/** Headers for GET API responses — public data, open CORS. */
const API_HEADERS_PUBLIC = {
  'Content-Type': 'application/json',
  'Access-Control-Allow-Origin': '*',
  'Cache-Control': 'no-cache',
};

/** Build headers for POST API responses — restricted CORS. */
function apiHeadersRestricted(request: Request): Record<string, string> {
  const origin = corsOrigin(request);
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
    'Cache-Control': 'no-cache',
  };
  if (origin) headers['Access-Control-Allow-Origin'] = origin;
  return headers;
}

async function handleEventIngest(request: Request, env: Env): Promise<Response> {
  const headers = apiHeadersRestricted(request);
  try {
    const body = await request.json() as Record<string, unknown>;

    if (!body.type || !body.agentId) {
      return new Response(JSON.stringify({ error: 'Missing required fields: type, agentId' }), {
        status: 400,
        headers,
      });
    }

    const sessionId = body.sessionId ? String(body.sessionId) : String(body.agentId);

    const event: AgentEvent = {
      type: String(body.type),
      agentId: String(body.agentId),
      agentName: String(body.agentName || body.agentId),
      sessionId,
      timestamp: String(body.timestamp || new Date().toISOString()),
      data: typeof body.data === 'object' && body.data !== null ? body.data as Record<string, unknown> : undefined,
      receivedAt: new Date().toISOString(),
    };

    // 1. Append to per-session key (strongly consistent get, no cross-session races)
    const sessionKey = `${SESSION_KEY_PREFIX}${sessionId}`;
    const existing = await env.MONITOR_KV.get<AgentEvent[]>(sessionKey, 'json');
    const events = existing ?? [];
    events.push(event);
    const trimmed = events.slice(-MAX_EVENTS_PER_SESSION);

    // 2. Update session index (tracks which sessions exist)
    const index = await env.MONITOR_KV.get<SessionEntry[]>(SESSION_INDEX_KEY, 'json') ?? [];
    const entry = index.find(s => s.id === sessionId);
    if (entry) {
      entry.lastSeen = event.receivedAt;
    } else {
      index.push({ id: sessionId, lastSeen: event.receivedAt });
    }
    // Keep most recent sessions, evict oldest
    index.sort((a, b) => b.lastSeen.localeCompare(a.lastSeen));
    const trimmedIndex = index.slice(0, MAX_SESSIONS);

    // 3. Write both in parallel
    await Promise.all([
      env.MONITOR_KV.put(sessionKey, JSON.stringify(trimmed), { expirationTtl: EVENT_TTL }),
      env.MONITOR_KV.put(SESSION_INDEX_KEY, JSON.stringify(trimmedIndex), { expirationTtl: EVENT_TTL }),
    ]);

    return new Response(JSON.stringify({ ok: true, session: sessionId, count: trimmed.length }), {
      status: 200,
      headers,
    });
  } catch {
    return new Response(JSON.stringify({ error: 'Invalid JSON body' }), {
      status: 400,
      headers,
    });
  }
}

async function handleAgentEvents(env: Env): Promise<Response> {
  // Read the session index (specific key = strongly consistent)
  const index = await env.MONITOR_KV.get<SessionEntry[]>(SESSION_INDEX_KEY, 'json');
  if (!index?.length) {
    return new Response(JSON.stringify({ events: [], count: 0 }), {
      headers: API_HEADERS_PUBLIC,
    });
  }

  // Fetch all session event arrays in parallel (specific keys = strongly consistent)
  const reads = index.map(s => env.MONITOR_KV.get<AgentEvent[]>(`${SESSION_KEY_PREFIX}${s.id}`, 'json'));
  const results = await Promise.all(reads);

  const allEvents: AgentEvent[] = [];
  for (const sessionEvents of results) {
    if (sessionEvents) allEvents.push(...sessionEvents);
  }

  allEvents.sort((a, b) => b.timestamp.localeCompare(a.timestamp));
  const publicAliases = new Map<string, PublicAgentAlias>();
  const capped = allEvents.slice(0, 100).map((event) => {
    const aliasKey = event.sessionId ?? event.agentId;
    let alias = publicAliases.get(aliasKey);
    if (!alias) {
      alias = createPublicAgentAlias(publicAliases.size + 1);
      publicAliases.set(aliasKey, alias);
    }
    return sanitizeAgentEvent(event, alias);
  });

  return new Response(JSON.stringify({ events: capped, count: capped.length }), {
    headers: API_HEADERS_PUBLIC,
  });
}

// ── Bug Tracker ──────────────────────────────────────────

interface BugEntry {
  id: string;
  tier: 1 | 2 | 3 | 4;
  kind: 'down' | 'drift' | 'exception' | 'error' | 'bad_outcome' | 'latency';
  severity: 'low' | 'medium' | 'high' | 'critical';
  source: string;
  infraRef: string;
  buildingId: string;
  message: string;
  timestamp: string;
  count?: number;
  data?: Record<string, unknown>;
}

interface BugSummary {
  active: number;
  byTier: { 1: number; 2: number; 3: number; 4: number };
  healthyEndpoints: number;
  totalEndpoints: number;
  resolved: number;
}

/** Worker name → infraRef mapping for error grouping. */
const WORKER_INFRA_MAP: Record<string, string> = {
  'blazesportsintel-worker-prod': 'blazesportsintel-worker-prod',
  'bsi-savant-compute': 'bsi-savant-compute',
  'bsi-cbb-ingest': 'bsi-cbb-ingest',
  'bsi-live-scores': 'bsi-live-scores',
  'bsi-intelligence-stream': 'bsi-intelligence-stream',
  'bsi-college-baseball-daily': 'bsi-college-baseball-daily',
  'bsi-synthetic-monitor': 'bsi-synthetic-monitor',
  'bsi-error-tracker': 'bsi-error-tracker',
  'bsi-prediction-api': 'bsi-prediction-api',
  'bsi-news-ticker': 'bsi-news-ticker',
  'bsi-ticker': 'bsi-ticker',
  'blaze-field-site': 'blaze-field-site',
  'blaze-field-site-prod': 'blaze-field-site',
  'blaze-field-do': 'blaze-field-do',
  'mini-games-api': 'mini-games-api',
  'college-baseball-mcp': 'college-baseball-mcp',
  'cbb-api': 'cbb-api',
  'bsi-sportradar-ingest': 'bsi-sportradar-ingest',
  'bsi-portal-sync': 'bsi-portal-sync',
  'bsi-analytics-events': 'bsi-analytics-events',
  'bsi-cbb-analytics': 'bsi-cbb-analytics',
};

/** Endpoint name → infraRef + buildingId mapping for monitor results. */
const ENDPOINT_MAP: Record<string, { infraRef: string; buildingId: string }> = {
  'Homepage':           { infraRef: 'blazesportsintel-worker-prod', buildingId: 'homepage' },
  'API Health':         { infraRef: 'blazesportsintel-worker-prod', buildingId: 'api-health' },
  'System Status':      { infraRef: 'bsi-synthetic-monitor',       buildingId: 'system-status' },
  'CB Scores':          { infraRef: 'bsi-cbb-ingest',              buildingId: 'cb-scores' },
  'CB Standings':       { infraRef: 'bsi-cbb-ingest',              buildingId: 'cb-standings' },
  'Scores Page':        { infraRef: 'blazesportsintel-worker-prod', buildingId: 'scores-page' },
  'Savant Leaderboard': { infraRef: 'bsi-savant-compute',          buildingId: 'savant-leaderboard' },
  'Savant Conference':  { infraRef: 'bsi-savant-compute',          buildingId: 'savant-conference' },
};

const LATENCY_THRESHOLD_MS = 500;

/** Snapshot of active bugs — persisted in KV for issue memory. */
interface BugSnapshot {
  bugIds: string[];
  timestamp: string;
}

interface BugReportPayload {
  bugs: BugEntry[];
  summary: BugSummary;
  timestamp: string;
}

async function collectBugReport(env: Env): Promise<BugReportPayload> {
  const bugs: BugEntry[] = [];
  let totalEndpoints = 0;
  let healthyEndpoints = 0;

  // Source A: Monitor results — failures, schema drift, AND latency
  try {
    const monitorRaw = await env.MONITOR_KV.get('summary:latest', 'text');
    if (monitorRaw) {
      const summary = JSON.parse(monitorRaw) as {
        results?: Array<{
          name: string;
          url?: string;
          status: number | string;
          ok: boolean;
          latencyMs?: number;
          schemaDrift?: boolean;
          error?: string;
          checkedAt?: string;
        }>;
      };

      if (summary.results) {
        totalEndpoints = summary.results.length;

        for (const result of summary.results) {
          const mapping = ENDPOINT_MAP[result.name];
          const infraRef = mapping?.infraRef ?? 'blazesportsintel-worker-prod';
          const buildingId = mapping?.buildingId ?? result.name.toLowerCase().replace(/\s+/g, '-');
          const ts = result.checkedAt ?? new Date().toISOString();

          // Endpoint down → Tier 3 (Ogre)
          if (!result.ok) {
            bugs.push({
              id: `monitor:down:${result.name}`,
              tier: 3,
              kind: 'down',
              severity: 'high',
              source: result.name,
              infraRef,
              buildingId,
              message: result.error ?? `${result.name} returned ${result.status}`,
              timestamp: ts,
              data: { status: result.status, error: result.error },
            });
          } else {
            healthyEndpoints++;

            // High latency → Tier 1 (Gnoll)
            if (result.latencyMs && result.latencyMs > LATENCY_THRESHOLD_MS) {
              bugs.push({
                id: `monitor:latency:${result.name}`,
                tier: 1,
                kind: 'latency',
                severity: 'low',
                source: result.name,
                infraRef,
                buildingId,
                message: `${result.name} responding in ${result.latencyMs}ms (>${LATENCY_THRESHOLD_MS}ms)`,
                timestamp: ts,
                data: { latencyMs: result.latencyMs, threshold: LATENCY_THRESHOLD_MS },
              });
            }
          }

          // Schema drift → Tier 2 (Bandit)
          if ('schemaDrift' in result && result.schemaDrift) {
            bugs.push({
              id: `monitor:drift:${result.name}`,
              tier: 2,
              kind: 'drift',
              severity: 'medium',
              source: result.name,
              infraRef,
              buildingId,
              message: `Schema drift detected on ${result.name}`,
              timestamp: ts,
              data: { schemaDrift: true },
            });
          }
        }
      }
    }
  } catch {
    // Monitor data unavailable — not fatal
  }

  // Source B: Error clusters from error-tracker (fingerprint-based)
  // Falls back to legacy individual-key listing if clusters don't exist yet
  try {
    let usedClusters = false;

    // Try cluster-based reads first (strongly consistent, no list() ceiling)
    const indexRaw = await env.ERROR_LOG.get('err-clusters:index', 'text');
    if (indexRaw) {
      const fingerprints = JSON.parse(indexRaw) as string[];
      if (fingerprints.length > 0) {
        usedClusters = true;
        const clusterReads = fingerprints.map(fp =>
          env.ERROR_LOG.get(`err-cluster:${fp}`, 'text'),
        );
        const clusterValues = await Promise.all(clusterReads);

        for (const raw of clusterValues) {
          if (!raw) continue;
          try {
            const cluster = JSON.parse(raw) as {
              fingerprint: string;
              worker: string;
              kind: string;
              message: string;
              count: number;
              firstSeen: string;
              lastSeen: string;
              sample: string;
            };

            const kind = cluster.kind === 'exception' ? 'exception'
              : cluster.kind === 'bad_outcome' ? 'bad_outcome'
              : 'error';

            const tier: 1 | 2 | 3 | 4 = cluster.count > 10 ? 3 : cluster.count > 3 ? 2 : 1;
            const severity = tier >= 3 ? 'high' : tier >= 2 ? 'medium' : 'low';

            bugs.push({
              id: `error:${cluster.worker}:${cluster.fingerprint}`,
              tier,
              kind: kind as BugEntry['kind'],
              severity,
              source: cluster.worker,
              infraRef: WORKER_INFRA_MAP[cluster.worker] ?? 'blazesportsintel-worker-prod',
              buildingId: cluster.worker,
              message: cluster.sample,
              timestamp: cluster.lastSeen,
              count: cluster.count,
              data: {
                errorCount: cluster.count,
                fingerprint: cluster.fingerprint,
                firstSeen: cluster.firstSeen,
              },
            });
          } catch {
            // Malformed cluster — skip
          }
        }
      }
    }

    // Legacy fallback: individual error keys (pre-cluster format)
    if (!usedClusters) {
      const today = new Date().toISOString().slice(0, 10);
      const yesterday = new Date(Date.now() - 86_400_000).toISOString().slice(0, 10);

      const [todayKeys, yesterdayKeys] = await Promise.all([
        env.ERROR_LOG.list({ prefix: `err:${today}`, limit: 20 }),
        env.ERROR_LOG.list({ prefix: `err:${yesterday}`, limit: 10 }),
      ]);

      const allKeys = [...todayKeys.keys, ...yesterdayKeys.keys].slice(0, 20);

      if (allKeys.length > 0) {
        const reads = allKeys.map(k => env.ERROR_LOG.get(k.name, 'text'));
        const values = await Promise.all(reads);

        const workerErrors = new Map<string, {
          count: number;
          latestType: string;
          latestMessage: string;
          latestTimestamp: string;
        }>();

        for (const raw of values) {
          if (!raw) continue;
          try {
            const entry = JSON.parse(raw) as {
              type?: string;
              worker?: string;
              message?: string;
              name?: string;
              timestamp?: string;
              logTimestamp?: string;
            };

            const worker = entry.worker ?? 'unknown';
            const errType = entry.type ?? 'error';
            const message = entry.message ?? entry.name ?? 'Unknown error';
            const ts = entry.timestamp ?? entry.logTimestamp ?? new Date().toISOString();

            const existing = workerErrors.get(worker);
            if (existing) {
              existing.count++;
              if (ts > existing.latestTimestamp) {
                existing.latestType = errType;
                existing.latestMessage = message;
                existing.latestTimestamp = ts;
              }
            } else {
              workerErrors.set(worker, {
                count: 1,
                latestType: errType,
                latestMessage: message,
                latestTimestamp: ts,
              });
            }
          } catch {
            // Malformed error entry — skip
          }
        }

        for (const [worker, info] of workerErrors) {
          const kind = info.latestType === 'exception' ? 'exception'
            : info.latestType === 'bad_outcome' ? 'bad_outcome'
            : 'error';

          const tier: 1 | 2 | 3 | 4 = info.count > 10 ? 3 : info.count > 3 ? 2 : 1;
          const severity = tier >= 3 ? 'high' : tier >= 2 ? 'medium' : 'low';

          bugs.push({
            id: `error:${worker}`,
            tier,
            kind: kind as BugEntry['kind'],
            severity,
            source: worker,
            infraRef: WORKER_INFRA_MAP[worker] ?? 'blazesportsintel-worker-prod',
            buildingId: worker,
            message: info.latestMessage,
            timestamp: info.latestTimestamp,
            count: info.count,
            data: { errorCount: info.count },
          });
        }
      }
    }
  } catch {
    // Error log unavailable — not fatal
  }

  // ── Dedup: merge monitor + error bugs that share the same infraRef ──
  // When a monitor "down" and error-tracker bug point to the same worker,
  // keep the higher-tier entry and fold the other's data into it.
  const byInfraRef = new Map<string, BugEntry[]>();
  for (const bug of bugs) {
    const group = byInfraRef.get(bug.infraRef) ?? [];
    group.push(bug);
    byInfraRef.set(bug.infraRef, group);
  }

  const dedupedBugs: BugEntry[] = [];
  for (const [, group] of byInfraRef) {
    if (group.length <= 1) {
      dedupedBugs.push(...group);
      continue;
    }

    // Separate monitor bugs from error-tracker bugs
    const monitorBugs = group.filter(b => b.id.startsWith('monitor:'));
    const errorBugs = group.filter(b => b.id.startsWith('error:'));

    // If there's a monitor:down bug AND error bugs for the same worker → merge
    const downBug = monitorBugs.find(b => b.kind === 'down');
    if (downBug && errorBugs.length > 0) {
      // Roll error details into the monitor bug (higher visibility)
      const totalErrors = errorBugs.reduce((sum, b) => sum + (b.count ?? 1), 0);
      downBug.count = (downBug.count ?? 0) + totalErrors;
      downBug.data = {
        ...downBug.data,
        errorCount: totalErrors,
        mergedErrors: errorBugs.map(b => ({
          message: b.message,
          count: b.count,
          fingerprint: b.data?.fingerprint,
        })),
      };
      // Use highest tier between monitor and error bugs
      for (const eb of errorBugs) {
        if (eb.tier > downBug.tier) downBug.tier = eb.tier;
      }
      // Keep the monitor:down bug, drop the individual error bugs
      dedupedBugs.push(downBug);
      // Keep non-down monitor bugs (latency, drift) separately
      dedupedBugs.push(...monitorBugs.filter(b => b !== downBug));
    } else {
      // No overlap — keep everything
      dedupedBugs.push(...group);
    }
  }

  // ── Issue memory: compare current bugs to previous snapshot ──
  let resolved = 0;
  try {
    const snapshotRaw = await env.MONITOR_KV.get('blazecraft:issues:snapshot', 'text');
    if (snapshotRaw) {
      const prevSnapshot = JSON.parse(snapshotRaw) as BugSnapshot;
      const currentIds = new Set(dedupedBugs.map(b => b.id));

      // Count bugs that were in the previous snapshot but no longer active
      let newlyResolved = 0;
      for (const prevId of prevSnapshot.bugIds) {
        if (!currentIds.has(prevId)) newlyResolved++;
      }

      // Read running total and increment
      const totalRaw = await env.MONITOR_KV.get('blazecraft:stats:resolved', 'text');
      const prevTotal = totalRaw ? parseInt(totalRaw, 10) || 0 : 0;
      resolved = prevTotal + newlyResolved;

      // Update running total only if new resolutions happened
      if (newlyResolved > 0) {
        await env.MONITOR_KV.put('blazecraft:stats:resolved', String(resolved));
      }
    } else {
      // First run — read existing resolved count
      const totalRaw = await env.MONITOR_KV.get('blazecraft:stats:resolved', 'text');
      resolved = totalRaw ? parseInt(totalRaw, 10) || 0 : 0;
    }

    // Write current snapshot for next comparison
    const snapshot: BugSnapshot = {
      bugIds: dedupedBugs.map(b => b.id),
      timestamp: new Date().toISOString(),
    };
    await env.MONITOR_KV.put('blazecraft:issues:snapshot', JSON.stringify(snapshot), {
      expirationTtl: 86400, // 24 hours — snapshot is only useful for recent comparisons
    });
  } catch {
    // Snapshot logic failure — non-fatal, resolved stays at 0
  }

  // Compute summary
  const byTier = { 1: 0, 2: 0, 3: 0, 4: 0 };
  for (const b of dedupedBugs) byTier[b.tier]++;

  const summary: BugSummary = {
    active: dedupedBugs.length,
    byTier,
    healthyEndpoints,
    totalEndpoints,
    resolved,
  };

  return { bugs: dedupedBugs, summary, timestamp: new Date().toISOString() };
}

async function handleBugs(env: Env): Promise<Response> {
  const payload = await collectBugReport(env);
  return new Response(JSON.stringify(payload), {
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
      'Cache-Control': 'public, max-age=15',
    },
  });
}

function buildResponse(object: R2ObjectBody, path: string, immutable: boolean): Response {
  const ext = path.includes('.') ? path.slice(path.lastIndexOf('.')) : '.html';
  const contentType = MIME_TYPES[ext] ?? 'application/octet-stream';

  const cacheControl = immutable
    ? 'public, max-age=31536000, immutable'
    : 'public, max-age=300';

  return new Response(object.body, {
    headers: {
      'Content-Type': contentType,
      'Cache-Control': cacheControl,
      'ETag': object.httpEtag,
      ...SECURITY_HEADERS,
    },
  });
}

function notFoundHtml(): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="noindex">
  <title>Blaze Field — Not Found</title>
  <style>
    body { margin:0; background:#0a0a0a; color:#f5f5f5; font-family:system-ui,sans-serif;
           display:flex; align-items:center; justify-content:center; min-height:100vh; }
    .box { text-align:center; }
    h1 { font-size:4rem; margin:0; color:#f97316; }
    p { font-size:1.2rem; margin:1rem 0; opacity:0.7; }
    a { color:#f97316; text-decoration:none; }
    a:hover { text-decoration:underline; }
  </style>
</head>
<body>
  <div class="box">
    <h1>404</h1>
    <p>Play not found. Return to the <a href="/">field</a>.</p>
  </div>
</body>
</html>`;
}
