'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';

interface EditorialData {
  date: string;
  content: string | null;
  meta: { source: string; fetched_at: string; timezone: string };
}

/** Minimal markdown-to-HTML: headings, bold, italic, lists, paragraphs. */
function markdownToHtml(md: string): string {
  return md
    .replace(/^### (.+)$/gm, '<h3 class="font-oswald text-xl uppercase tracking-wide text-burnt-orange mt-8 mb-3">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 class="font-oswald text-2xl uppercase tracking-wide text-burnt-orange mt-10 mb-4">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 class="font-oswald text-3xl uppercase tracking-wide text-burnt-orange mt-10 mb-5">$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/^- (.+)$/gm, '<li class="ml-4 list-disc">$1</li>')
    .replace(/(<li.*<\/li>\n?)+/g, (match) => `<ul class="my-4 space-y-1">${match}</ul>`)
    .replace(/^(?!<[hul])(.*\S.*)$/gm, '<p class="my-3 leading-relaxed">$1</p>');
}

export function generateStaticParams() {
  return [];
}

export default function DailyEditorialPage() {
  const params = useParams<{ date: string }>();
  const date = params.date;
  const [data, setData] = useState<EditorialData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!date) return;

    async function fetchEditorial() {
      try {
        const res = await fetch(`/api/college-baseball/editorial/daily/${date}`);
        if (!res.ok) throw new Error(`Failed to fetch editorial: ${res.status}`);
        const json: EditorialData = await res.json();
        setData(json);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Unknown error');
      } finally {
        setLoading(false);
      }
    }

    fetchEditorial();
  }, [date]);

  if (loading) {
    return (
      <div className="min-h-screen bg-midnight text-white flex items-center justify-center">
        <p className="font-cormorant text-lg text-gray-400 animate-pulse">Loading editorial...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-midnight text-white flex items-center justify-center">
        <p className="font-cormorant text-lg text-red-400">{error}</p>
      </div>
    );
  }

  const displayDate = date
    ? new Date(date + 'T12:00:00').toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      })
    : '';

  return (
    <main className="min-h-screen bg-midnight text-white">
      <article className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
        {/* Header */}
        <header className="mb-10 border-b border-charcoal pb-8">
          <div className="mb-4 flex items-center gap-3">
            <span className="inline-block rounded bg-burnt-orange/20 px-3 py-1 text-xs font-semibold uppercase tracking-widest text-burnt-orange">
              AI-Generated Daily Digest
            </span>
          </div>
          <h1 className="font-oswald text-4xl uppercase tracking-wide text-white sm:text-5xl">
            College Baseball Daily
          </h1>
          <time className="mt-3 block font-cormorant text-lg text-gray-400" dateTime={date}>
            {displayDate}
          </time>
        </header>

        {/* Content */}
        {data?.content ? (
          <div
            className="font-cormorant text-lg leading-relaxed text-gray-200 prose-headings:font-oswald prose-strong:text-white"
            dangerouslySetInnerHTML={{ __html: markdownToHtml(data.content) }}
          />
        ) : (
          <div className="rounded-lg border border-charcoal bg-charcoal/30 p-8 text-center">
            <p className="font-cormorant text-lg text-gray-400">
              No editorial content available for this date.
            </p>
          </div>
        )}

        {/* Footer attribution */}
        <footer className="mt-16 border-t border-charcoal pt-8 text-center">
          <p className="font-cormorant text-sm text-gray-500">
            Generated by Claude AI in Austin Humphrey&apos;s editorial voice
          </p>
          {data?.meta && (
            <p className="mt-1 font-mono text-xs text-gray-600">
              Source: {data.meta.source} &middot; {data.meta.timezone}
            </p>
          )}
        </footer>
      </article>
    </main>
  );
}
