# Blaze Sports Intel NIL Pipeline configuration
project:
  name: "Blaze Sports Intel NIL Valuation"
  disclaimer: "Estimated value, not contractual."

logging:
  level: "INFO"

database:
  url: "postgresql+psycopg2://postgres:postgres@localhost:5432/blaze_nil"
  echo: false

storage:
  raw_path: "storage/raw"

redis:
  host: "localhost"
  port: 6379
  ttl_seconds: 900

features:
  attention_weights:
    social_followers: 0.5
    social_engagement: 0.3
    search_interest: 0.2
  attention_decay_days: 14
  performance_weights:
    points: 0.4
    assists: 0.2
    rebounds: 0.2
    efficiency: 0.2
  market_adjustment:
    Baseball: 1.05
    Football: 1.15
    Basketball: 1.10
    "Track & Field": 0.95

modeling:
  stage_a_params:
    learning_rate: 0.1
    n_estimators: 100
    max_depth: 3
  stage_b_params:
    learning_rate: 0.1
    n_estimators: 200
    max_depth: 4
  shrinkage_prior: 0.5
  shrinkage_strength: 10.0

context:
  schools:
    BSI University:
      market_size: 1.2
      tv_exposure: 0.9
    Summit College:
      market_size: 0.8
      tv_exposure: 0.7
    Redwood State:
      market_size: 1.5
      tv_exposure: 1.1
