/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 170d9e1ec7aef73241953c6375dd15f9)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface ProductionEnv {
		EVENTS_DB: D1Database;
		ENVIRONMENT: "production";
	}
	interface Env {
		EVENTS_DB: D1Database;
		ENVIRONMENT: "production" | "development";
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT">> {}
}
