# Cloudflare Workers Configuration - College Football Intelligence Engine
# Purpose: Real-time CFB game tracking, EPA analytics, and upset probability modeling
# Deployment: wrangler deploy (from workers/cfb-intelligence/)

name = "blaze-cfb-intelligence"
compatibility_date = "2025-01-01"
main = "index.ts"

# Worker Type
workers_dev = true

# Triggers - Run every 5 minutes during game days
[triggers]
crons = ["*/5 * * * *"]

# Environment Variables
[vars]
# These will be set via wrangler secret put
# NCAA_API_KEY = ""
# ESPN_API_KEY = ""
# SPORTSRADAR_API_KEY = ""

# D1 Database (College Football data)
[[d1_databases]]
binding = "DB"
database_name = "blaze-cfb"
database_id = "placeholder-uuid"  # Set after: wrangler d1 create blaze-cfb

# KV Namespace (Real-time caching)
[[kv_namespaces]]
binding = "CFB_CACHE"
id = "placeholder-uuid"  # Set after: wrangler kv:namespace create "CFB_CACHE"
preview_id = "placeholder-uuid"  # Set after: wrangler kv:namespace create "CFB_CACHE" --preview

# R2 Bucket (Historical data archives)
[[r2_buckets]]
binding = "GAME_DATA"
bucket_name = "blaze-game-archives"

# Analytics Engine (Optional - for tracking metrics)
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "cfb_intelligence_analytics"

# Build Configuration
[build]
command = "echo 'No build step required for simple TypeScript worker'"

# Compatibility Flags
[compatibility_flags]
nodejs_compat = true
