/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime --config workers/bsi-live-scores/wrangler.toml workers/bsi-live-scores/env.d.ts` (hash: a5b3551cd51f1523bd91ba311b2700d6)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "LiveScoresBroadcaster";
	}
	interface Env {
		ENVIRONMENT: "production";
		LIVE_SCORES: DurableObjectNamespace<import("./index").LiveScoresBroadcaster>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT">> {}
}
