/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime --config workers/bsi-savant-compute/wrangler.toml workers/bsi-savant-compute/env.d.ts` (hash: d4866f38f0f8985747fcf9fb28fb10d8)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		KV: KVNamespace;
		DB: D1Database;
	}
}
interface Env extends Cloudflare.Env {}
