/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime --config workers/bsi-college-baseball-daily/wrangler.toml workers/bsi-college-baseball-daily/env.d.ts` (hash: 39b2db63fd5c4c5b0b5303d58663fd26)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		KV: KVNamespace;
		DIGEST_BUCKET: R2Bucket;
	}
}
interface Env extends Cloudflare.Env {}
