name = "bsi-proxy-worker"
main = "src/index.ts"
compatibility_date = "2024-10-01"
workers_dev = true
usage_model = "bundled"

[vars]
# Required: Origin for the upstream API or Next.js app the worker proxies to.
UPSTREAM_BASE_URL = "https://dev.bsi.local"
# Optional: Where the WebGPU sample lives (used in the manifest endpoint).
WEBGPU_DEMO_ORIGIN = "https://dev.bsi.local/webgpu"
# Optional: Comma separated CORS allowlist.
ALLOWED_ORIGINS = "http://localhost:3000,https://dev.bsi.local"
# Optional: Override cache TTL (seconds, <= 60).
CACHE_TTL_SECONDS = "30"
