name = "bsi-dev-worker"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[vars]
UE_PROXY_TARGET = "https://example.com/ue"

[[kv_namespaces]]
binding = "FEATURE_FLAGS"
id = "bsi_feature_flags"
preview_id = "bsi_feature_flags_preview"

[dev]
port = 8787

[observability]
enabled = true
