#!/usr/bin/env sh

set -e

echo "Running repository secret scan before push..."
git ls-files -z | xargs -0 npx --no-install secretlint \
  --secretlintrc .secretlintrc.json \
  --secretlintignore .secretlintignore
